const alfa = {
	"0": "ZERO",
	"1": "ONE",
	"2": "TWO",
	"3": "THREE",
	"4": "FOUR",
	"5": "FIVE",
	"6": "SIX",
	"7": "SEVEN",
	"8": "EIGHT",
	"9": "NINER",
  "a": "ALPHA",
  "b": "BRAVO",
  "c": "CHARLIE",
  "d": "DELTA",
  "e": "ECHO",
  "f": "FOXTROT",
  "g": "GOLF",
  "h": "HOTEL",
  "i": "INDIA",
  "j": "JULIETT",
  "k": "KILO",
  "l": "LIMA",
  "m": "MIKE",
  "n": "NOVEMBER",
  "o": "OSCAR",
  "p": "PAPA",
  "q": "QUEBEC",
  "r": "ROMEO",
  "s": "SIERRA",
  "t": "TANGO",
  "u": "UNIFORM",
  "v": "VICTOR",
  "w": "WHISKEY",
  "x": "X-RAY",
  "y": "YANKEE",
  "z": "ZULU"
};
const flags = {
  "0":"flags/0.gif",
  "1":"flags/1.gif",
  "2":"flags/2.gif",
  "3":"flags/3.gif",
  "4":"flags/4.gif",
  "5":"flags/5.gif",
  "6":"flags/6.gif",
  "7":"flags/7.gif",
  "8":"flags/8.gif",
  "9":"flags/9.gif",
  "a":"flags/a.gif",
  "b":"flags/b.gif",
  "c":"flags/c.gif",
  "d":"flags/d.gif",
  "e":"flags/e.gif",
  "f":"flags/f.gif",
  "g":"flags/g.gif",
  "h":"flags/h.gif",
  "i":"flags/i.gif",
  "j":"flags/j.gif",
  "k":"flags/k.gif",
  "l":"flags/l.gif",
  "m":"flags/m.gif",
  "n":"flags/n.gif",
  "o":"flags/o.gif",
  "p":"flags/p.gif",
  "q":"flags/q.gif",
  "r":"flags/r.gif",
  "s":"flags/s.gif",
  "t":"flags/t.gif",
  "u":"flags/u.gif",
  "v":"flags/v.gif",
  "w":"flags/w.gif",
  "x":"flags/x.gif",
  "y":"flags/y.gif",
  "z":"flags/z.gif"
};


const inter = {
	"0": "",
	"1": "",
	"2": "",
	"3": "",
	"4": "",
	"5": "",
	"6": "",
	"7": "",
	"8": "",
	"9": "",
	"a":"Ich habe Taucher im Wasser; halten Sie Abstand",
	"b":"Ich lade/lösche/befördere gefährliche Güter",
	"c":"Ja",
	"d":"Ich bin manövrierbehindert; halten Sie Abstand",
	"e":"Ich ändere Kurs nach Stb",
	"f":"Ich bin manövrierunfähig; treten Sie mit mir in Verbindung",
	"g":"Ich brauche einen Lotsen",
	"h":"Ich habe einen Lotsen an Bord",
	"i":"Ich ändere Kurs nach Bb",
	"j":"Ich habe Feuer an Bord und gefährliche Güter geladen, halten Sie sich von mir fern",
	"k":"Ich möchte mit Ihnen kommunizieren",
	"l":"Bringen Sie Ihr Fahrzeug sofort zum Stehen",
	"m":"Meine Maschine ist gestoppt und ich mache keine Fahrt durchs Wasser",
	"n":"Nein",
	"o":"Mann über Bord",
	"p":"Im Hafen: Alle Mann an Bord / Auf See: Netze an Hindernis festgekommen (Fischerei) ",
	"q":"An Bord ist alles gesund; ich bitte um freie Verkehrserlaubnis",
	"r":"Ich habe Ihr Signal erhalten",
	"s":"Meine Maschinen fahren nach achtern",
	"t":"Trawler - Abstand halten",
	"u":"Ihnen droht Gefahr",
	"v":"Ich brauche Hilfe",
	"w":"Ich brauche medizinische Hilfe",
	"x":"Brechen Sie Ihr Manöver ab und achten Sie auf meine Signale",
	"y":"Ich treibe vor Anker",
	"z":"Ich brauche einen Schlepper",
	"ac":"Ich verlasse mein Schiff",
	"ad":"Ich verlasse mein Schiff, welches einen atomaren Unfall erlitten hat und von dem eine mögliche Strahlengefahr ausgeht",
	"ae":"Ich muss mein Schiff verlassen",
	"ae1":"Ich möchte mein Schiff verlassen, bin aber nicht in der Lage dazu",
	"ae2":"Ich werde mein Schiff verlassen, wenn Sie nicht bei mir bleiben und mir helfen",
	"af":"Ich beabsichtige nicht, mein Schiff zu verlassen",
	"af1":"Beabsichtigen Sie, Ihr Schiff zu verlassen?",
	"ag":"Sie sollten Ihr Schiff so schnell wie möglich verlassen",
	"ah":"Sie sollten Ihr Schiff nicht verlassen",
	"ai":"Schiff (identifiziert durch Position und/oder Name, falls nötig) muss verlassen werden",
	"aj":"Ich hatte einen schweren atomaren Unfall. Nähern Sie sich mit Vorsicht",
	"ak":"Ich hatte einen atomaren Unfall an Bord",
	"al":"Arzt an Bord",
	"am":"Haben Sie einen Arzt?",
	"an":"Benötige Arzt",
	"an1":"Benötige Arzt - Habe schwere Verbrennungen",
	"an2":"Benötige Arzt - Habe Strahlungsopfer",
	"ao":"Opferzahl noch nicht bekannt",
	"ao1":"Wie viele verletzte?",
	"ao2":"Wie viele tote?",
	"ap":"Ich habe ... (Zahl) Opfer",
	"aq":"Ich habe kranke/verletzte Person (oder Anzahl Personen) - dringend aufzunehmen",
	"az1":"Ich kann nicht landen/wassern, aber kann verletzte/kranke Person aufnehmen",
	"at":"Schicken Sie verletzte/kranke Personen zu mir",
	"au":"Ich bin gezwungen in Ihrer Nähe (oder in angegebener Position) zu wassern ",
	"av":"Ich lande/wassere (in angegebener Position) um Mannschaft von Fahrzeug/Flugzeug aufzusammeln",
	"aw":"Sie sollten hier landen/wassern",
	"ax":"Strahlen Sie Ihren Scheinwerfer möglichst unterbrochen vertikal auf eine Wolke, und wenn Sie mein Flugzeug sehen, strahlen Sie gegen den Wind aufs Wasser, um mir wassern zu ermöglichen",
	"ax1":"Soll ich meinen Scheinwerfer möglichst unterbrochen vertikal auf eine Wolke strahlen, und wenn ich Ihr Flugzeug sehe, gegen den Wind aufs Wasser strahlen, um Ihnen Wassern zu ermöglichen?",
	"ay":"Ich werde auf Ihrem Deck landen; (Sie sollten mit ... Knoten auf Kurs ... steuern)",
	"az":"Ich kann nicht landen/wassern, aber kann Mannschaft aufnehmen",
	"ba":"Sie können nicht auf dem Deck landen",
	"ba1":"Sie können nicht auf dem Deck landen; können Sie Mannschaft heraufholen?",
	"ba2":"Sie können nicht auf dem Deck landen, können Sie verletzte/kranke Person heraufholen?",
	"bb":"Sie dürfen auf meinem Deck landen",
	"bb1":"Sie dürfen auf meinem Deck landen; Ich kann Sie vorne aufnehmen",
	"bb2":"Sie dürfen auf meinem Deck landen; Ich kann sie mitten im Schiff aufnehmen",
	"bb3":"Sie dürfen auf meinem Deck landen; Ich kann Sie hinten aufnehmen",
	"bb4":"Sie dürfen auf meinem Deck landen, aber ich kann Sie nicht aufnehmen",
	"bc":"Ich habe Kommunikation mit Flugzeug in Not auf Frequenz 2182 kHz hergestellt",
	"bc1":"Können Sie mit dem Flugzeug kommunizieren?",
	"bd":"Ich habe Kommunikation mit Flugzeug in Not auf Frequenz ... kHz hergestellt",
	"be":"Ich habe Kommunikation mit Flugzeug in Not auf Frequenz ... mHz hergestellt",
	"bf":"Flugzeug ist an angegebener Position notgewassert und braucht sofort Hilfe",
	"bg":"Flugzeug noch schwimmend",
	"bh":"Ich habe Flugzeug zur angegebenen Uhrzeit in Position ... fliegend auf Kurs ... gesichtet",
	"bh1":"Flugzeug flog in großer Höhe",
	"bh2":"Flugzeug flog in geringer Höhe",
	"bi":"Ich fliege zu wahrscheinlichem Standort von Fahrzeug in Not",
	"bi1":"Ich fliege in geringer Höhe nahe dem Fahrzeug",
	"bj":"Ich kreise über dem Unfallgebiet",
	"bj1":"Ein Flugzeug kreist über dem Unfallgebiet",
	"bk":"Sie fliegen darüber",
	"bk1":"Fliege ich darüber?",
	"bl":"Ich habe Motorprobleme, setze Flug dennoch fort",
	"bm":"Sie sollten Objekt per Fallschirm windwärts absetzen. Markieren Sie es durch Rauch- oder Lichtsignal",
	"bm1":"Ich werde Objekt per Fallschirm windwärts absetzen und es durch Rauch- oder Lichtsignal markieren",
	"bm2":"Ich werde Ausrüstung per Fallschirm absetzen",
	"bm3":"Rettungsinsel wird windwärts per Fallschirm abgesetzt",
	"bo":"Wir werden per Fallschirm abspringen",
	"bp":"Flugzeug nähert sich, um sich an Suche zu beteiligen. Erwartete Ankunfszeit über Unfallgebiet wie angezeigt",
	"bq":"Die Geschwindigkeit über Grund meines Flugzeugs beträgt ... (Knoten oder Stundenkilometer)",
	"bq1":"Was ist die Geschwindigkeit über Grund Ihres Flugzeugs?",
	"br":"Ich brauche dringend einen Hubschrauber",
	"br1":"Ich brauche dringend einen Hubschrauber um Personen aufzunehmen",
	"br2":"Ich brauche dringend Hubschrauber mit Arzt",
	"br3":"Ich brauche dringend Hubschrauber um verletzte/kranke Person aufzunehmen",
	"br4":"Ich brauche dringend einen Hubschrauber mit Rettungsinsel",
	"bs":"Sie sollten Hubschrauber/Boot mit Krankentrage schicken",
	"bu":"Boot/Hubschrauber kommt um Kranke/Verletzte mitzunehmen",
	"bt":"Hubschrauber kommt jetzt (oder zur angegebenen Zeit) zu ihnen",
	"bt1":"Hubschrauber kommt jetzt (oder zur angegebenen Zeit) zu ihnen, um Personen aufzunehmen",
	"bt2":"Hubschrauber mit Arzt kommt jetzt (oder zu angegebener Zeit) zu Ihnen",
	"bt3":"Hubschrauber kommt jetzt (oder zur angegebenen Zeit) zu ihnen, um verletzte/kranke Personen aufzunehmen",
	"bt4":"Hubschrauber mit Rettungsinsel kommt jetzt zu ihnen",
	"bv":"Kann keinen Hubschrauber schicken",
	"bw":"Der missweisende Kurs damit Sie auf mich (oder auf Fahrzeug/Position) zusteuern können ist... (zu angegebenem Zeitpunkt)",
	"bx":"Der missweisende Kurs, der den Hubschrauber zur Basis zurückführt, ist...",
	"by":"Zeigen Sie mir den missweisenden Kurs an, damit ich auf Sie (oder auf Fahrzeug/Position) zusteuern kann?",
	"bz":"Ihre magnetische Peilung von mir (oder von Fahrzeug/Position) ist... (zu angegebenem Zeitpunkt)",
	"ca":"Was ist meine magnetische Peilung von Ihnen (oder von Fahrzeug/Position)?",
	"cb":"Ich brauche dringend Hilfe",
	"cb1":"Ich habe gefährliche Schlagseite und brauche dringend Hilfe",
	"cb2":"Ich habe beschädigtes Ruderwerk und brauche dringend Hilfe",
	"cb3":"Ich habe eine schwere Unruhe an Bord und brauche dringend Hilfe",
	"cb4":"Ich bin auf Grund gelaufen und brauche dringend Hilfe",
	"cb5":"Ich treibe und brauche dringend Hilfe",
	"cb6":"Ich brenne und brauche dringend Hilfe",
	"cb7":"Ich bin leck geworden und brauche dringend Hilfe",
	"cb8":"Meine Antriebswelle ist kaputt und ich brauche dringend Hilfe",
	"cc":"Ich bin (oder angegebenes Fahrzeug ist) in Not auf Position... (oder Peilung und Entfernung von angegebenem Standort) und braucht dringend Hilfe",
	"cd":"Ich brauche Unterstützung durch ... (Wasser/Proviant/Treibstoff/Pumpausrüstung/Brandbekämpfungsausrüstung/Ärztliche Hilfe/Schleppen/Überlebensfahrzeuge/Beistehendes Fahrzeug/Eisbrecher)",
	"ce":"Ich versuche, Ihnen die benötigte Hilfe zu holen",
	"cf":"Signale von Fahrzeug/Flugzeug, das Hilfe benötigt, kommen aus Peilung ... von mir aus (Position falls nötig)",
	"cg":"Stehen Sie bereit, um mir (oder angegebenem Fahrzeug) zu helfen",
	"cg1":"Ich stehe bereit, um Ihnen (oder angegebenem Fahrzeug) zu helfen",
	"ch":"Es wird berichtet, angegebenes Fahrzeug benötigt Hilfe in Position ... (oder Peilung/Distanz von Standort ...)",
	"ch1":"angegebenes Feuerschiff/angegebener Leuchtturm benötigt Hilfe",
	"ch2":"Raumschiff ist in Position ... abgestürzt und benötigt Hilfe",
	"ci":"Aufgelaufenes Schiff in Position ... benötigt Hilfe",
	"cj":"Benötigen Sie Hilfe?",
	"cj1":"Benötigen Sie sofort Hilfe?",
	"cj2":"Benötigen Sie weitere Hilfe?",
	"cj3":"Welche Hilfe benötigen Sie?",
	"cj4":"Können Sie ohne Hilfe fortfahren?",
	"ck":"Von mir (oder angegebenem Fahrzeug) wird keine Hilfe mehr benötigt",
	"cl":"Ich bat Hilfe an, aber sie wurde abgelehnt",
	"cm":"Ein oder mehrere Fahrzeug/e helfen dem Fahrzeug in Not",
	"cm1":"Es wird berichtet, dass Fahrzeug/Flugzeug in Not Hilfe bekommt",
	"cn":"Sie sollten alle mögliche Hilfe geben",
	"cn1":"Sie sollten sofort helfen, um Überlebende aufzunehmen",
	"cn2":"Sie sollten Überlebensfahrzeuge zu angegebenem Fahrzeug schicken",
	"co":"Ihnen (oder angegebenem Fahrzeug) kann nicht geholfen werden",
	"co1":"Ich kann die benötigte Hilfe nicht geben",
	"cp":"Ich komme (oder angegebenes Fahrzeug kommt) Ihnen zur Hilfe",
	"cp1":"SAR-Flugzeug kommt Ihnen zur Hilfe",
	"cq":"Ruf an alle Stationen/unbekannte Stationen",
	"cr":"Ich komme Fahrzeug in Position ... zur Hilfe",
	"cs":"Was ist der Name oder das Identifikationsszeichen Ihres Fahrzeugs/Ihrer Station?",
	"ct":"Ich erwarte (oder angegebenes Fahrzeug erwartet) Sie zur angegebenen Zeit zu erreichen",
	"cu":"Hilfe kommt zu angegebener Zeit",
	"cu1":"Ich kann Ihnen helfen",
	"cv":"Ich kann Ihnen nicht helfen",
	"cw":"Boot/Floß ist an Bord",
	"cw1":"Boot/Floß ist in Sicherheit",
	"cw2":"Boot/Floß ist in Sicht",
	"cw3":"Boot/Floß treibt",
	"cw4":"Boot/Floß ist auf Grund",
	"cw5":"Boot/Floß ist längsseits",
	"cw6":"Boot/Floß ist beschädigt",
	"cw7":"Boot/Floß ist gesunken",
	"cw8":"Boot/Floß ist gekentert",
	"cx":"Boote sind unbrauchbar",
	"cx1":"Boote sind aufgrund von Wetterbedingungen unbrauchbar",
	"cx2":"Boote auf Stb aufgrund von Schieflage unbrauchbar",
	"cx3":"Boote auf Bb aufgrund von Schieflage unbrauchbar",
	"cx4":"Boote können nicht zum Ausbooten von Personen benutzt werden",
	"cx5":"Boote können nicht zum längsseitig werden benutzt werden",
	"cx6":"Boote können nicht benutzt werden, um Sie zu erreichen",
	"cx7":"Ich kann kein Boot schicken",
	"cy":"Boote kommen zu Ihnen",
	"cy1":"Boot/Floß begibt sich zum Ufer",
	"cy2":"Boot/Floß hat Ufer erreicht",
	"cz":"Sie sollten Booten/Flößen Windschatten geben",
	"cz1":"Sie sollten Öl ablassen, um See zu glätten",
	"da":"Boote/Flöße sollten sich so nah wie möglich an Fahrzeug begeben, um Personen aufzunehmen",
	"db":"Drehen Sie ein Boot/Floß mit Leine",
	"dc":"Boot sollte dort landen, wo Flagge oder Licht gezeigt wird",
	"dd":"Boote dürfen nicht längsseitig kommen",
	"dd1":"Boote dürfen (nach angegebener Zeit) nicht landen",
	"de":"Von ... (Namen oder Identifikation der anrufenden Station vorangestellt)",
	"df":"Ich habe (Zahl) Boote zur Verfügung",
	"dg":"Ich habe ein Motorboot (oder (Zahl) Motorboote)",
	"dh":"Ich habe kein Boot/Floß",
	"dh1":"Ich habe kein Motorboot",
	"dh2":"Haben Sie Boote mit Funkausrüstung?",
	"dh3":"Wie viele Motorboote stehen Ihnen zur Verfügung?",
	"dh4":"Wie viele Boote stehen Ihnen zur Verfügung?",
	"di":"Ich brauche Boote für (Zahl) Personen",
	"dj":"Brauchen Sie ein Boot?",
	"dk":"Sie sollten alle verfügbaren Boote schicken",
	"dk1":"Sie sollten mein Boot zurückschicken",
	"dk2":"Können Sie ein Boot schicken?",
	"dl":"Ich kann ein Boot schicken",
	"dl1":"Ich schicke ein Boot",
	"dm":"Sie sollten nach den Booten/Flößen suchen",
	"dn":"Ich habe das Boot/Floß gefunden",
	"dn1":"Haben Sie etwas vom Boot/Floß gesehen oder gehört?",
	"do":"Halten Sie Ausschau nach Boot/Floß in Peilung ... Entfernung... von mir (oder von angegebener Position)",
	"dp":"Es gibt ein Boot/Floß in Peilung ... Entfernung ... von mir (oder von angegebener Position)",
	"dq":"Ein leeres Boot/Floß wurde in Position ... (oder Peilung ... von angegebenem Ort, Entfernung ...) gesichtet",
	"dr":"Haben Sie manövrierunfähiges Fahrzeug/Flugzeug in ungefährer Position ... gesichtet?",
	"ds":"Ich habe manövrierunfähiges Flugzeug in Position ... zur angegebenen Zeit gesichtet",
	"dt":"Ich habe manövrierunfähiges Fahrzeug in Position ... zur angegebenen Zeit gesichtet",
	"dt1":"Ich habe manövrierunfähiges Fahrzeug in Position ... zur angegebenen Zeit scheinbar ohne Funkausrüstung gesichtet",
	"du":"Ich treibe mit ... Knoten auf Kurs ...",
	"dv":"Ich treibe",
	"dv1":"Ich treibe ab",
	"dw":"Fahrzeug (Name oder Erkennungszeichen) treibt nahe Position ...",
	"dx":"Ich sinke (Position falls nötig)",
	"dy":"Fahrzeug (Name oder Erkennungszeichen) ist gesunken in Position ...",
	"dy1":"Haben Sie das Fahrzeug sinken sehen?",
	"dy2":"Wo ist das Fahrzeug gesunken?",
	"dy3":"Wurde bestätigt, dass Fahrzeug (Name oder Erkennungszeichen) gesunken ist?",
	"dy4":"Wie tief ist das Wasser dort, wo Fahrzeug gesunken ist?",
	"dz":"angegebenes Fahrzeug/Flugzeug scheint in Not zu sein",
	"dz1":"Ist angegebenes Fahrzeug/Flugzeug in Not?",
	"dz2":"Wie lautet der Name (oder das Erkennungszeichen) des Fahrzeugs, welches in Not ist?",
	"ea":"Haben Sie etwas von einem Fahrzeug oder Flugzeug in Not gehört? (Ungefähre Position oder Peilung und Entfernung von angegebenem Ort)",
	"ea1":"Haben Sie Neuigkeiten von einem vermisst gemeldeten/in Not befindlichen Fahrzeug/Flugzeug in diesem Gebiet?",
	"eb":"Es gibt ein Fahrzeug/Flugzeug in Not in Position ... (oder Peilung/Entfernung von mir, oder in Himmelsrichtung ... oder Position unbekannt)",
	"ed":"Ihr Notsignal wurde verstanden",
	"ed1":"Ihr Notsignal wurde verstanden, die nächste Rettungsstation wird informiert",
	"ef":"SOS/MAYDAY wurde abgebrochen",
	"ef1":"Wurde SOS/MAYDAY abgebrochen?",
	"eg":"Haben Sie SOS/MAYDAY zu angegebener Zeit gehört?",
	"eg1":"Hören Sie 2182kHz nach EPIRB-Signalen ab?",
	"eg2":"Ich höre 2182kHz nach EPIRB-Signalen ab",
	"eg3":"Haben Sie auf 2182kHz ein EPIRB-Signal erhalten?",
	"eg4":"Ich habe auf 2182kHz ein EPIRB-Signal erhalten",
	"eg5":"Hören Sie ... mHz nach EPIRB-Signalen ab?",
	"eg6":"Ich höre ... mHz nach EPIRB-Signalen ab",
	"eg7":"Haben Sie auf ... mHz ein EPIRB-Signal erhalten?",
	"eg8":"Ich habe auf ... mHz ein EPIRB-Signal erhalten",
	"ej":"Ich habe ein Notsignal von angegebener Küstenstation erhalten",
	"ej1":"Haben Sie ein Notsignal von angegebener Küstenstation erhalten?",
	"ek":"Ich habe in Position ... ein Notsignal gesichtet",
	"ek1":"Es wurde eine Explosion gesehen/gehört (Anzeige von Position oder Richtung und Zeit)",
	"ek2":"Haben Sie Notsignal von Überlebensfahrzeug gesehen/gehört?",
	"el":"Wiederholen Sie Standort des Notfalls",
	"el1":"Auf welcher Position befindet sich Fahrzeug in Not?",
	"em":"Gibt es andere Fahrzeuge/Flugzeuge in der Nähe des Fahrzeugs/Flugzeugs in Not?",
	"en":"Sie sollten versuchen, mit Fahrzeug/Flugzeug in Not Kontakt aufzunehmen",
	"eo":"Ich kann Fahrzeug/Flugzeug in Not aufgrund schlechter Sicht nicht finden",
	"ep":"Ich habe Sie aus den Augen verloren",
	"eq":"Ich erwarte, Standort des Fahrzeugs/Flugzeugs in Not zu angegebener Zeit zu erreichen",
	"eq1":"Zeigen Sie Ihre erwartete Ankunftszeit am Standort des Fahrzeugs/Flugzeugs in Not an",
	"er":"Sie sollten Ihre Position zur angegebenen Zeit anzeigen",
	"et":"Meine Position zur angegebenen Zeit war ...",
	"eu":"Meine gegenwärtige Position ist ... (oder Peilung/Entfernung von angegebenem Ort)",
	"eu1":"Was ist Ihre gegenwärtige Position?",
	"ev":"Meine gegenwärtige Position, Kurs und Geschwindigkeit sind ..., ..., ... Knoten",
	"ev1":"Was ist Ihre gegenwärtige Position, Kurs und Geschwindigkeit?",
	"ew":"Meine Position wird durch ungefähre Berechnung bestimmt",
	"ew1":"Meine Position wird durch Sichtpeilung bestimmt",
	"ew2":"Meine Position wird durch astronomische Beobachtungen bestimmt",
	"ew3":"Meine Position wird durch Funkbake bestimmt",
	"ew4":"Meine Position wird durch Radar bestimmt",
	"ew5":"Meine Position wird durch elektronische Standortbestimmung bestimmt",
	"ex":"Meine Position ist zweifelhaft",
	"ey":"Ich bin mir bezüglich meiner Position sicher",
	"ey1":"Sind Sie sich bezüglich Ihrer Position sicher?",
	"ez":"Laut Peilfunkstellen, die ich kontrolliere, beträgt Ihre Position ... (zur angegebenen Zeit)",
	"ez1":"Können Sie mir meine Position laut Peilfunkstellen, die Sie kontrollieren geben?",
	"fa":"Können Sie mir meine Position geben?",
	"fb":"Können Fahrzeuge in meiner Nähe (oder in Nähe der Position ...) bitte Position, Kurs und Geschwindigkeit anzeigen?",
	"fc":"Sie sollten Ihre Position durch visuelle oder akustische Signale anzeigen",
	"fc1":"Sie sollten Ihre Position durch Raketen oder Leuchtgeschosse anzeigen",
	"fc2":"Sie sollten Ihre Position durch visuelle Signale anzeigen",
	"fc3":"Sie sollten Ihre Position durch akustische Signale anzeigen",
	"fc4":"Sie sollten Ihre Position durch Scheinwerfer anzeigen",
	"fc5":"Sie sollten Ihre Position durch Rauchsignal anzeigen",
	"fd":"Meine Position wird durch visuelle oder akustische Signale angezeigt",
	"fd1":"Meine Position wird durch Raketen oder Leuchtgeschosse angezeigt",
	"fd2":"Meine Position wird durch visuelle Signale angezeigt",
	"fd3":"Meine Position wird durch akustische Signale angezeigt",
	"fd4":"Meine Position wird durch Scheinwerfer angezeigt",
	"fd5":"Meine Position wird durch Rauchsignal angezeigt",
	"fe":"Ich begebe mich mit Höchstgeschwindigkeit zum Unfallort, erwarte Ankunft zu angegebener Zeit",
	"fe1":"Begeben Sie sich zum Unfallort? Falls ja, wann erwarten Sie Ankunft?",
	"ff":"Ich habe SOS/MAYDAY von Fahrzeug/Flugzeug (Name oder Erkennungszeichen) in Position ... zu angegebener Zeit abgefangen",
	"ff1":"Ich habe SOS/MAYDAY von Fahrzeug/Flugzeug (Name oder Erkennungszeichen) in Position ... zu angegebener Zeit abgefangen; ich habe seitdem nichts gehört",
	"fg":"Angegebene Position mit SOS/MAYDAY von Fahrzeug/Flugzeug war ... (oder Peilung/Entfernung zu angegebenem Standort)",
	"fg1":"Welche Position wurde mit SOS/MAYDAY von Fahrzeug/Flugzeug angegeben?",
	"fh":"Die mit SOS/MAYDAY gegebene Position ist falsch. Die tatsächliche Position ist ...",
	"fi":"Die mit SOS/MAYDAY von Fahrzeug gegebene Position ist falsch. Ich habe seine Peilung per Peilgerät und kann Peilungen mit  anderem Schiff austauschen.",
	"fj":"Unfallort (oder Standort des Überlebensfahrzeugs) ist markiert",
	"fj1":"Unfallort (oder Standort des Überlebensfahrzeugs) ist markiert durch Flamme oder Rauch",
	"fj2":"Unfallort (oder Standort des Überlebensfahrzeugs) ist markiert durch Seemarkierung",
	"fj3":"Unfallort (oder Standort des Überlebensfahrzeugs) ist markiert durch Farbmarkierung",
	"fj4":"Unfallort (oder Standort des Überlebensfahrzeugs) ist markiert durch Funkbake",
	"fj5":"Unfallort (oder Standort des Überlebensfahrzeugs) ist markiert durch Wrack",
	"fk":"Ist Unfallort (oder Standort des Überlebensfahrzeug) markiert?",
	"fl":"Steuern Sie zum Kurs ... (oder folgen Sie mir) um Unfallort zu erreichen",
	"fm":"Sichtkontakt mit Fahrzeug ist unbeständig",
	"fn":"Ich habe jeden Kontakt zum Fahrzeug verloren",
	"fo":"Ich bleibe in Ihrer Nähe",
	"fo1":"Ich bleibe nachts in Ihrer Nähe",
	"fp":"Geschätzte Abdrift des Überlebensfahrzeugs beträgt ... Grad mit ... Knoten",
	"fp1":"Was ist die geschätzte Abdrift des Überlebensfahrzeugs?",
	"fq":"Sie sollten das Fahrzeug/Flugzeug auf Ihre Position steuern",
	"fq1":"Soll ich das Fahrzeug/Flugzeug zu meiner Position steuern?",
	"fr":"Ich (oder angegebenes Fahrzeug) ist für Koordination der Suche zuständig",
	"fr1":"Führen Sie Suchmuster... ab... Uhr durch. Startkurs ... Suchgeschwindigkeit ... Knoten",
	"fr2":"Führen Sie eine Radarsuche durch, Schiffe fahren in loser Linie nebeneinander in Abständen von ... Meilen zwischen Schiffen. Anfangskurs ... Suchgeschwindigkeit ... Knoten",
	"fr3":"angegebenem Fahrzeug (Name oder Erkennungszeichen) wird Streckennummer ... zugewiesen",
	"fr4":"angegebene Fahrzeuge Abstand zwischen Schiffen zu ... Meilen ändern",
	"fr5":"Abstand zwischen Schiffen zu ... Meilen ändern",
	"fr6":"Suchgeschwindigkeit ab jetzt ... Knoten",
	"fr7":"Den Kurs jetzt (oder zur angegebenen Zeit) wie nötig zum nächsten Streckenabschnitt ändern",
	"fs":"Bitte übernehmen Sie die Zuständigkeit für Suche im Sektor zwischen Peilung ... und ... vom Fahrzeug in Not",
	"ft":"Bitte übernehmen Sie die Zuständigkeit für Suche im Sektor zwischen Position ... und Position ...",
	"fu":"Suchgebiet des Flugzeugs ist zwischen Position ... und Position ...",
	"fv":"Suche wird aufgrund schlechter Bedingungen abgebrochen",
	"fw":"Sie sollten in der Nähe von Position ... suchen",
	"fx":"Soll ich in der Nähe von Position ... suchen?",
	"fy":"Ich bin im Suchgebiet",
	"fy1":"Sind Sie im Suchgebiet?",
	"fz":"Sie sollten die Suche gemäß Anweisung bis auf Weiteres fortsetzen",
	"fz1":"Ich suche weiter",
	"fz2":"Suchen Sie weiter?",
	"fz3":"Soll ich weitersuchen?",
	"ga":"Ich kann nicht weitersuchen",
	"gb":"Sie sollten die Suche abbrechen und zurückkehren oder Ihre Reise fortsetzen",
	"gc":"Berichten Sie von den Suchergebnissen",
	"gc1":"Suchergebnis negativ. Ich suche weiter",
	"gc2":"Ich habe einen Unfallort abgesucht, aber keine Spuren von Wrack oder Überlebenden gefunden",
	"gc3":"Ich habe Ölspuren am wahrscheinlichen Unfallort entdeckt",
	"gd":"Vom vermissten Fahrzeug/Flugzeug wurde nichts gesehen oder gehört",
	"gd1":"Haben Sie etwas vom vermissten Fahrzeug/Flugzeug zu berichten?",
	"gd2":"Haben Sie Wrack oder Wrackteile gesehen?",
	"ge":"Fahrzeug/Flugzeug wurde in Position ... gefunden",
	"gf":"Ich habe Fahrzeug/Flugzeug in Not in Position ... gefunden",
	"gg":"Fahrzeug/Flugzeug wurde zuletzt zur angegebenen Zeit in Position ... auf Kurs ... gemeldet",
	"gh":"Ich habe Überlebensfahrzeug in Position ... (oder Peilung... Entfernung... von mir) gesichtet",
	"gi":"Überlebensfahrzeuge werden in der Nähe von Position ... vermutet",
	"gj":"Wrack ist in Position ... gemeldet",
	"gj1":"Wrack ist in Position ... gemeldet. Keine Überlebenden scheinen in der Nähe zu sein",
	"gk":"Flugzeugwrack wurde in Position ... gefunden",
	"gl":"Ich habe Wrack des Fahrzeugs/Flugzeugs gefunden (wenn nötig Ortsangabe durch Position oder Peilung/Entfernung von bestimmtem Standort)",
	"gm":"Ich kann mein Fahrzeug nicht retten",
	"gm1":"Ich kann mein Fahrzeug nicht retten; bleiben Sie mir so nah wie möglich",
	"gn":"Sie sollten Personen abziehen",
	"gn1":"Ich wünsche Abzug von Personen. Notbesatzung bleibt an Bord",
	"gn2":"Ich werde Personen abziehen",
	"gn3":"Können Sie Personen abziehen?",
	"go":"Ich kann keine Personen abziehen",
	"gp":"Sie sollten sich zur Rettung des Fahrzeugs (oder notgewasserten Flugzeugs) in Position ... begeben",
	"gq":"Ich kann mich aufgrund des Wetters nicht zur Rettung begegen. Sie sollten alles tun, was Sie können",
	"gr":"Fahrzeug kommt Ihnen (oder angegebenem Fahrzeug/Flugzeug) auf Kurs ... mit Geschwindigkeit ... Knoten zur Hilfe",
	"gr1":"Sie sollten Kurs und Geschwindigkeit des Fahrzeugs, das mir (oder angegebenem Fahrzeug/Flugzeug) zur Hilfe kommt, anzeigen",
	"gs":"Ich versuche Rettung mit Hosenboje",
	"gt":"Ich versuche mich durch Leinenschussgerät zu verbinden",
	"gt1":"Halten Sie Ausschau nach Raketenleine",
	"gu":"Es ist nicht sicher, eine Rakete abzufeuern",
	"gv":"Sie sollten versuchen, mir eine Leine zuzuschicken",
	"gv1":"Haben Sie ein Leinenschussgerät?",
	"gv2":"Können Sie sich durch ein Leinenschussgerät verbinden?",
	"gv3":"Ich habe kein Leinenschussgerät",
	"gw":"Mann über Bord. Bitte nehmen Sie ihn auf (Positionsangabe falls nötig)",
	"gx":"Berichten Sie Ergebnisse der Rettung",
	"gx1":"Was haben Sie (oder Rettungsfahrzeug/-flugzeug) aufgesammelt?",
	"gy":"Ich habe (oder Rettungsfahrzeug/-flugzeug hat) Wrack(teile) aufgesammelt.",
	"gz":"Alle Personen gerettet",
	"gz1":"Alle Personen verloren",
	"ha":"Ich habe (oder Rettungsfahrzeug/-flugzeug hat) ... verletzte Personen geborgen",
	"hb":"Ich habe (oder Rettungsfahrzeug/-flugzeug hat) ... Überlebende geborgen",
	"hc":"Ich habe (oder Rettungsfahrzeug/-flugzeug hat) ... Leichen geborgen",
	"hd":"Kann ich gerettete Personen an Sie übergeben?",
	"hf":"Ich habe Überlebende im Wasser aufgefunden, Position ... (oder Peilung ... Entfernung ... von angegebenem Ort)",
	"hg":"Ich habe Überlebende in Überlebensfahrzeug(en) gefunden, Position ... (oder Peilung ... Entfernung ... von angegebenem Ort)",
	"hj":"Ich habe Überlebende auf Treibeis gefunden, Position ...",
	"hk":"Ich habe Leichen gefunden, Position ... (oder Peilung ... Entfernung ... von angegebenem Ort)",
	"hl":"Überlebende noch nicht aufgefunden",
	"hl1":"Ich suche noch nach Überlebenden",
	"hl2":"Haben Sie Überlebende gefunden? Falls ja, in welcher Position?",
	"hm":"Überlebende sind in schlechtem Zustand. Ärztliche Hilfe wird dringend benötigt",
	"hm1":"Überlebende sind in schlechtem Zustand",
	"hm2":"Überlebende sind in gutem Zustand",
	"hm3":"Zustand der Überlebenden nicht bestimmt",
	"hm4":"In welchem Zustand sind die Überlebenden?",
	"hn":"Sie sollten sich zur Position ... begeben, um Überlebende aufzusammeln",
	"ho":"Überlebende von Treibeis aufsammeln, Position ...",
	"ho1":"Überlebende von sinkendem Fahrzeug/Flugzeug aufsammeln",
	"hp":"Überlebende wurden noch nicht aufgesammelt",
	"hp1":"Wurden Überlebende aufgesammelt?",
	"hq":"Übergeben Sie Überlebende an mein Fahrzeug (oder angegebenes Fahrzeug)",
	"hq1":"Haben Sie Überlebende an Bord?",
	"hr":"Sie sollten jede mögliche Information von Überlebenden sammeln",
	"ht":"Sie sollten Position der Überlebenden durch Pyrosignale anzeigen",
	"hv":"Hatten Sie einen Zusammenstoß?",
	"hw":"Ich bin (oder angegebenes Fahrzeug ist) mit einem Überwasserfahrzeug kollidiert",
	"hw1":"Ich bin (oder das angegebene Fahrzeug ist) mit einem Feuerschiff kollidiert",
	"hw2":"Ich bin (oder das angegebene Fahrzeug ist) mit einem U-Boot kollidiert",
	"hw3":"Ich bin (oder das angegebene Fahrzeug ist) mit einem unbekannten Fahrzeug kollidiert",
	"hw4":"Ich bin (oder das angegebene Fahrzeug ist) mit einem Unterwassergegenstand kollidiert",
	"hw5":"Ich bin (oder das angegebene Fahrzeug ist) mit einer Tonne kollidiert",
	"hw6":"Ich bin (oder das angegebene Fahrzeug ist) mit einem Eisberg kollidiert",
	"hw7":"Ich bin (oder das angegebene Fahrzeug ist) mit Treibeis kollidiert",
	"hx":"Wurden Sie im Zusammenstoß beschädigt?",
	"hx1":"Ich habe schwere Schäden oberhalb der Wasserlinie",
	"hx2":"Ich habe schwere Schäden unterhalb der Wasserlinie",
	"hx3":"Ich habe leichte Schäden oberhalb der Wasserlinie",
	"hx4":"Ich habe leichte Schäden unterhalb der Wasserlinie",
	"hy":"Das Fahrzeug (Name oder Erkennungszeichen), mit dem ich zusammengestoßen bin, ist gesunken",
	"hy1":"Das Fahrzeug (Name oder Erkennungszeichen), mit dem ich zusammengestoßen bin, hat seine Reise fortgesetzt",
	"hy2":"Ich weiß nicht, was mit dem Fahrzeug, mit dem ich zusammengestoßen bin, passiert ist",
	"hy3":"Hat das Fahrzeug, mit dem Sie zusammengestoßen sind, seine Reise fortgesetzt?",
	"hy4":"Wie ist der Name (oder das Erkennungszeichen) des Fahrzeugs, mit dem Sie zusammengestoßen sind?",
	"hy5":"Wie ist der Name (oder das Erkennungszeichen) des Fahrzeugs, welches mit mir zusammengestoßen ist? Mein Name (oder Erkennungszeichen) ist ...",
	"hy6":"Wo ist das Fahrzeug, mit dem Sie zusammengestoßen sind?",
	"hz":"Es gab einen Zusammenstoß zwischen angegebenen Fahrzeugen (Namen oder Erkennungszeichen)",
	"ia":"Ich habe Schaden am Vorsteven erhalten",
	"ia1":"Ich habe Schaden am Heckrahmen erhalten",
	"ia2":"Ich habe Schaden an Seitenplatte über Wasser erhalten",
	"ia3":"Ich habe Schaden an Seitenplatte unter Wasser erhalten",
	"ia4":"Ich habe Schaden an Bodenplatte erhalten",
	"ia5":"Ich habe Schaden am Heizraum erhalten",
	"ia6":"Ich habe Schadne am Maschinenraum erhalten",
	"ia7":"Ich habe Lukenschäden erhalten",
	"ia8":"Ich habe Lenkgetriebeschäden erhalten",
	"ia9":"Ich habe Propellerschäden erhalten",
	"ib":"Welche Schäden haben Sie erhalten?",
	"ib1":"Mein Fahrzeug ist schwer beschädigt",
	"ib2":"Ich habe leichte Schäden",
	"ib3":"Ich habe keine Schäden erhalten",
	"ib4":"Der Ausmaß des Schadens ist noch unbekannt",
	"ic":"Können Schäden auf See behoben werden?",
	"ic1":"Können Schäden auf See ohne Hilfe behoben werden?",
	"ic2":"Wie lange werden Sie brauchen, um Schäden zu beheben?",
	"id":"Schäden können auf See behoben werden",
	"id1":"Schäden können auf See ohne Hilfe behoben werden",
	"id2":"Schäden wurden behoben",
	"if":"Schäden können nicht auf See behoben werden",
	"if1":"Schäden können nicht ohne Hilfe auf See behoben werden",
	"ig":"Schäden können in ... Stunden behoben werden",
	"ij":"Ich versuche, mit eigenen Mitteln fortzufahren, aber ich erbitte, dass Sie mit mir in Kontakt bleiben",
	"ik":"Ich kann mich mit ... Knoten fortbewegen",
	"il":"Ich kann mich nur langsam fortbewegen",
	"il1":"Ich kann mich nur mit einem Motor fortbewegen",
	"il2":"Ich kann mich nicht mit eigener Kraft fortbewegen",
	"il3":"Können Sie sich fortbewegen?",
	"im":"Ich erbitte, bis auf Weiteres begleitet zu werden",
	"in":"Ich brauche einen Taucher",
	"in1":"Ich brauche einen Taucher, um Propeller freizumachen",
	"in2":"Ich brauche einen Taucher, um Rumpf zu prüfen",
	"in3":"Ich brauche einen Taucher, um Lecksegel anzubringen",
	"in4":"Ich brauche einen Taucher, um meinen Anker freizumachen",
	"io":"Ich habe keinen Taucher",
	"ip":"Ein Taucher wird so bald wie möglich (oder zu angegebener Zeit) geschickt",
	"iq":"Taucher ist tauchkrank und benötigt Druckkammerbehandlung",
	"ir":"Ich bin mit U-Boot-Vermessungsarbeiten (Unterwasserarbeiten) beschäftigt. Halten Sie sich von mir fern und fahren Sie langsam",
	"it":"Ich habe Feuer an Bord",
	"it1":"Ich habe Feuer an Bord und gefährliche Güter geladen, halten Sie sich von mir fern",
	"it2":"Fahrzeug (Name oder Erkennungszeichen) hat Feuer an Bord",
	"it3":"Haben Sie Feuer an Bord?",
	"iu":"Fahrzeug (Name oder Erkennungszeichen) hat Feuer an Bord in Position ...",
	"iv":"Wo ist der Brand?",
	"iv1":"Ich habe Brand im Maschinenraum",
	"iv2":"Ich habe Brand im Heizraum",
	"iv3":"Ich habe Brand im Laderaum oder in der Ladung",
	"iv4":"Ich habe Brand im Passagier- oder Mannschaftsquartier",
	"iv5":"Mein Öl brennt",
	"iw":"Brand ist unter Kontrolle",
	"ix":"Brand nimmt zu",
	"ix1":"Ich kann den Brand nicht ohne Hilfe unter Kontrolle bringen",
	"ix2":"Der Brand wurde nicht gelöscht",
	"iy":"Ich kann den Brand ohne Hilfe unter Kontrolle bringen",
	"iy1":"Können Sie den Brand ohne Hilfe unter Kontrolle bringen?",
	"iz":"Der Brand ist gelöscht",
	"iz1":"Ich flute Abteilung, um Brand zu löschen",
	"iz2":"Ist der Brand gelöscht?",
	"ja":"Ich benötige Feuerlöschgeräte",
	"ja1":"Ich benötige Schaumfeuerlöscher",
	"ja2":"Ich benötige CO2-Feuerlöscher",
	"ja3":"Ich benötige Tetrachlorkohlenstoff-Feuerlöscher",
	"ja4":"Ich benötige Material für Schaumfeuerlöscher",
	"ja5":"Ich benötige Material für CO2-Feuerlöscher",
	"ja6":"Ich benötige Material für Tetrachlorkohlenstoff-Feuerlöscher",
	"ja7":"Ich benötige Wasserpumpen",
	"jb":"Es besteht Explosionsgefahr",
	"jc":"Es besteht keine Explosionsgefahr",
	"jc1":"Besteht Explosionsgefahr?",
	"jd":"Es gab eine Explosion im Kessel",
	"jd1":"Es gab eine Explosion im Tank",
	"jd2":"Es gab eine Explosion in der Ladung",
	"jd3":"Weitere Explosionen sind möglich",
	"jd4":"Es besteht Vergiftungsgefahr",
	"je":"Haben Sie Opfer aufgrund Explosion?",
	"jf":"Ich bin (oder angegebenes Fahrzeug ist) auf Grund gelaufen in Position...",
	"jf0":"Ich bin (oder angegebenes Fahrzeug ist) auf felsigen Grund gelaufen",
	"jf1":"Ich bin (oder angegebenes Fahrzeug ist) auf weichen Grund gelaufen",
	"jf2":"Ich bin (oder angegebenes Fahrzeug ist) vorne auf Grund gelaufen",
	"jf3":"Ich bin (oder angegebenes Fahrzeug ist) mittschiffs auf Grund gelaufen",
	"jf4":"Ich bin (oder angegebenes Fahrzeug ist) achtern auf Grund gelaufen",
	"jf5":"Ich bin (oder angegebenes Fahrzeug ist) bei Flut vorne auf Grund gelaufen",
	"jf6":"Ich bin (oder angegebenes Fahrzeug ist) bei Flut mittschiffs auf Grund gelaufen",
	"jf7":"Ich bin (oder angegebenes Fahrzeug ist) bei Flut achtern auf Grund gelaufen",
	"jf8":"Ich bin (oder angegebenes Fahrzeug ist) mit ganzer Fahrzeuglänge auf Grund gelaufen",
	"jf9":"Ich bin (oder angegebenes Fahrzeug ist) bei Flut mit ganzer Fahrzeuglänge auf Grund gelaufen",
	"jg":"Ich bin auf Grund; Ich bin in Gefahr",
	"jh":"Ich bin auf Grund; Ich bin nicht in Gefahr",
	"ji":"Sind Sie auf Grund gelaufen?",
	"j1":"Wie war Ihr Tiefgang, als Sie auf Grund liefen?",
	"ji2":"Auf welchem Untergrund sind Sie auf Grund gelaufen?",
	"ji3":"Zu welcher Tide sind Sie auf Grund gelaufen?",
	"ji4":"Welcher Teil Ihres Fahrzeugs ist auf Grund gelaufen?",
	"jj":"Mein maximaler Tiefgang, als ich auf Grund gelaufen bin, betrug ... Fuß/Meter",
	"jk":"Ich bin bei Flut auf Grund gelaufen",
	"jk1":"Ich bin bei Halbtide auf Grund gelaufen",
	"jk2":"Ich bin bei Ebbe auf Grund gelaufen",
	"jl":"Ihnen droht die Gefahr, auf Grund zu laufen",
	"jl1":"Ihnen droht die Gefahr, auf Grund zu laufen; Nähern Sie sich mir nicht von der Steuerbordseite",
	"jl2":"Ihnen droht die Gefahr, auf Grund zu laufen; Nähern Sie sich mir nicht von der Backbordseite",
	"jl3":"Ihnen droht die Gefahr, auf Grund zu laufen; Nähern Sie sich mir nicht von vorne",
	"jl4":"Ihnen droht die Gefahr, auf Grund zu laufen; Nähern Sie sich mir nicht von achtern",
	"jm":"Ihnen droht die Gefahr, bei Niedrigwasser auf Grund zu laufen",
	"jn":"Sie sollten das Fahrzeug in Position ... auf Strand setzen",
	"jn1":"Sie sollten das Fahrzeug dort auf Strand setzen, wo Flagge oder Licht gezeigt wird",
	"jn2":"Ich mus das Fahrzeug auf Strand setzen",
	"jo":"Ich bin flott",
	"jo1":"Ich bin vorne flott",
	"jo2":"Ich bin achtern flott",
	"jo3":"Ich kann bei umgehender Hilfe flott gemacht werden",
	"jo4":"Sind Sie (oder angegebenes Fahrzeug) noch flott?",
	"jo5":"Wann erwarten Sie, flott zu sein?",
	"jp":"Ich werfe ab, um wieder flott zu werden",
	"jp1":"Ich werfe Ladung ab, um wieder flott zu werden",
	"jp2":"Ich werfe Treibstoff ab, um wieder flott zu werden",
	"jp3":"Ich werfe alles vorn bewegliche ab, um wieder flott zu werden",
	"jp4":"Ich werfe alles achtern bewegliche ab, um wieder flott zu werden",
	"jq":"Ich kann nicht wieder flott werden, ohne abzuwerfen",
	"jq1":"Ich kann nicht wieder flott werden, ohne Ladung abzuwerfen",
	"jq2":"Ich kann nicht wieder flott werden, ohne Treibstoff abzuwerfen",
	"jq3":"Ich kann nicht wieder flott werden, ohne alles vorn bewegliche abzuwerfen",
	"jq4":"Ich kann nicht wieder flott werden, ohne alles achtern bewegliche abzuwerfen",
	"jr":"Ich erwarte (oder angegebenes Fahrzeug erwartet), wieder flott zu werden",
	"jr1":"Ich erwarte (oder angegebenes Fahrzeug erwartet), zu angegebener Zeit wieder flott zu werden",
	"jr2":"Ich erwarte (oder angegebenes Fahrzeug erwartet), bei Tageslicht wieder flott zu werden",
	"jr3":"Ich erwarte (oder angegebenes Fahrzeug erwartet), bei Flut wieder flott zu werden",
	"jr4":"Ich erwarte (oder angegebenes Fahrzeug erwartet), bei verbesserter Sicht wieder flott zu werden",
	"jr5":"Ich erwarte (oder angegebenes Fahrzeug erwartet), bei verbesserter Wetterlage wieder flott zu werden",
	"jr6":"Ich erwarte (oder angegebenes Fahrzeug erwartet), bei niedrigerem Tiefgang wieder flott zu werden",
	"jr7":"Ich erwarte (oder angegebenes Fahrzeug erwartet), bei Ankunft von Schleppern wieder flott zu werden",
	"js":"Ist zu erwarten, dass Sie (oder angegebenes Fahrzeug) wieder flott werden?",
	"js1":"Ist zu erwarten, dass Sie oder angegebenes Fahrzeug) zu angegebener Zeit wieder flott werden?",
	"js2":"Ist zu erwarten, dass Sie (oder angegebenes Fahrzeug) bei Tageslicht wieder flott werden?",
	"js3":"Ist zu erwarten, dass Sie (oder angegebenes Fahrzeug) bei Flut wieder flott werden?",
	"js4":"Ist zu erwarten, dass Sie (oder angegebenes Fahrzeug) bei verbesserter Sicht wieder flott werden?",
	"js5":"Ist zu erwarten, dass Sie (oder angegebenes Fahrzeug) bei verbesserter Wetterlage wieder flott werden?",
	"js6":"Ist zu erwarten, dass Sie (oder angegebenes Fahrzeug) bei niedrigerem Tiefgang wieder flott werden?",
	"js7":"Ist zu erwarten, dass Sie (oder angegebenes Fahrzeug) bei Ankunft von Schleppern wieder flott werden?",
	"jt":"Ich kann wieder flott werden, wenn ein Anker für mich ausgelegt wird",
	"jt1":"Ich kann ohne Hilfe wieder flott werden",
	"jt2":"Können Sie mir helfen, wieder flott zu werden?",
	"ju":"Ich kann mit keinen jetzt verfügbaren Mitteln wieder flott werden",
	"jv":"Begleiten Sie mich zur Position ... wenn ich wieder flott bin?",
	"jw":"Ich bin leck geworden",
	"jw1":"Leck ist gefährlich",
	"jw2":"Leck verursacht gefährliche Krängung",
	"jw3":"Leck überlastet meine Pumpen",
	"jx":"Leck nimmt rasant zu",
	"jx1":"Ich kann Leck nicht abdichten",
	"jy":"Leck kann kontrolliert werden, wenn es nicht schlimmer wird",
	"jy1":"Ich brauche weitere Pumpausrüstung, um Leck zu kontrollieren",
	"jy2":"Leck ist unter Kontrolle",
	"jy3":"Leck wurde abgedichtet",
	"jz":"Sind Sie leck geworden?",
	"jz1":"Können Sie das Leck abdichten?",
	"jz2":"Ist das Leck gefährlich?",
	"ka":"Ich brauche dringend ein Lecksegel",
	"ka1":"Ich habe das Lecksegel eingesetzt. Ich kann ohne Hilfe fortfahren",
	"ka2":"Können Sie das Lecksegel einsetzen?",
	"kb":"Ich habe ... (Fuß oder Meter) Wasser im Laderaum",
	"kc":"Mein Laderaum ist geflutet",
	"kc1":"Wie viele Abteile sind geflutet?",
	"kd":"... (Zahl) Abteilungen sind geflutet",
	"ke":"Schotten halten Wasserdruck gut stand",
	"ke1":"Ich brauche Holz um Schotten zu stützen",
	"kf":"Ich brauche einen Schlepper (oder (Anzahl) Schlepper))",
	"kg":"Brauchen Sie einen Schlepper?",
	"kg1":"Ich brauche keinen Schlepper",
	"kh":"Schlepper kommen zu Ihnen. Erwartete Ankunft zur angegebenen Zeit",
	"kh1":"Schlepper mit Lotsen kommt zu Ihnen",
	"kh2":"Sie sollten auf Schlepper warten",
	"ki":"Es stehen keine Schlepper zur Verfügung",
	"ki1":"Schlepper können nicht ausfahren",
	"kj":"Ich schleppe einen Unterwassergegenstand",
	"kj1":"Ich schleppe einen Schwimmkörper",
	"kj2":"Ich schleppe ein Ziel",
	"kk":"Schleppen unter gegenwärtigen Witterungsbedingungen unmöglich",
	"kk1":"Schleppen sehr schwierig",
	"kk2":"Ich kann mich nicht verbinden, aber werde es versuchen, wenn sich Bedingungen bessern",
	"kk3":"Ich kann mich heute Nacht nicht verbinden; werde es bei Tageslicht versuchen",
	"kk4":"Können Sie Schleppen mit Ihren Motoren unterstützen?",
	"kl":"Ich muss das Schleppen vorübergehend abbrechen",
	"kl1":"Sie sollten das Schleppen vorübergehend abbrechen",
	"km":"Ich kann Sie (oder angegebenes Fahrzeug) ins Schlepptau nehmen",
	"km1":"Soll ich Sie ins Schlepptau nehmen?",
	"kn":"Ich kann Sie (oder angegebenes Fahrzeug) nicht ins Schlepptau nehmen",
	"kn1":"Ich kann Sie (oder angegebenes Fahrzeug) nicht ins Schlepptau nehmen, aber ich werde um Hilfe bitten",
	"kn2":"Ich kann Sie (oder angegebenes Fahrzeug) nicht ins Schlepptau nehmen, aber ich kann Personen mitnehmen",
	"ko":"Sie sollten sich bemühen, Fahrzeug (Name oder Erkennungszeichen) ins Schlepptau zu nehmen",
	"ko1":"Sie sollten melden, ob Sie Fahrzeug (Name oder Erkennungszeichen) ins Schlepptau genommen haben",
	"ko2":"Können Sie mich (oder angegebenes Fahrzeug) ins Schlepptau nehmen?",
	"kp":"Sie sollten mich zum nächsten Hafen oder Ankerplatz (oder angegebenen Ort) schleppen",
	"kp1":"Ich werde Sie zum nächsten Hafen oder Ankerplatz (oder angegebenen Ort) schleppen",
	"kp2":"Ich brauche schnellstmöglich eine Anlaufstelle oder einen Ankerplatz",
	"kq":"Machen Sie sich bereit, ins Schlepptau genommen zu werden",
	"kq1":"Ich bin bereit, ins Schlepptau genommen zu werden",
	"kq2":"Machen Sie sich bereit, mich (oder angegebenes Fahrzeug) zu schleppen",
	"kq3":"Ich bin bereit, Sie zu schleppen",
	"kq4":"Machen Sie sich bereit, das Schleppen fortzusetzen",
	"kq5":"Ich bin bereit, das Schleppen fortzusetzen",
	"kr":"Alles bereit zum Schleppen",
	"kr1":"Ich fange an zu schleppen",
	"kr2":"Sie sollten anfangen zu schleppen",
	"kr3":"Ist alles zum Schleppen bereit?",
	"ks":"Sie sollten eine Schleppleine schicken",
	"ks1":"Ich habe die Schleppleine genommen",
	"kt":"Sie sollten mir eine Trosse schicken",
	"kt1":"Ich schicke eine Trosse",
	"ku":"Ich kann keine Trosse schicken",
	"ku1":"Ich habe keine (oder keine andere) Trosse",
	"ku2":"Ich habe keine Stahltrosse",
	"ku3":"Haben Sie eine Trosse?",
	"kv":"Ich beabsichtige, meine Trosse einzusetzen",
	"kv1":"Ich beabsichtige, Ihre Trosse einzusetzen",
	"kw":"Sie sollten Ihre Trosse bereithalten",
	"kw1":"Trosse ist bereit",
	"kw2":"Sie sollten eine weitere Trosse bereithalten",
	"kw3":"Sie sollten Ersatztrosse bereithalten",
	"kw4":"Ersatztrosse ist bereit",
	"kw5":"Sie sollten Stahltrosse bereithalten",
	"kw6":"Stahltrosse ist bereit",
	"kx":"Sie sollten bereit sein, die Trosse entgegenzunehmen",
	"kx1":"Ich bin bereit, die Trosse entgegenzunehmen",
	"kx2":"Sie sollten näher kommen, um Trosse entgegenzunehmen",
	"kx3":"Ich komme näher, um Trosse entgegenzunehmen",
	"kx4":"Ich habe Trosse entgegengenommen",
	"ky":"Länge der Trosse ist ... Faden",
	"kz":"Sie sollten Trosse verkürzen (oder Distanz zwischen Fahrzeugen verkürzen)",
	"kz1":"Ich verkürze die Trosse (oder ich verkürze Distanz zwischen Fahrzeugen)",
	"kz2":"Sie sollten die Trosse einholen",
	"kz3":"Ich hole die Trosse ein",
	"kz4":"Sie sollten die Lose einholen",
	"kz5":"Ich hole die Lose ein",
	"la":"Trosse ist gerissen",
	"la1":"Trosse droht zu reißen",
	"la2":"Trosse ist beschädigt",
	"la3":"Sie sollten die Trossen verstärken",
	"la4":"Ich verstärke die Trossen",
	"lb":"Sie sollten die Trosse an Ihre Ankerkette befestigen",
	"lb1":"Die Trosse ist an der Ankerkette befestigt",
	"lb2":"Sie sollten die Trosse an Drahtseil befestigen",
	"lb3":"Trosse ist an Drahtseil befestigt",
	"lb4":"Meine Trosse ist fest",
	"lb5":"Ist Ihre Trosse fest?",
	"lc":"Sie sollten achtern festmachen und mich steuern",
	"ld":"Sie sollten Ihre Trosse um ... Faden fieren",
	"le":"Ich bin kurz davor, meine Trosse zu fieren",
	"le1":"Ich fiere meine Trosse",
	"le2":"Ich habe meine Trosse gefiert",
	"le3":"Ich werde Drahtseil, an dem Trosse angebracht ist, fieren",
	"le4":"Wie viel von der Trosse soll ich fieren?",
	"lf":"Sie sollten aufhören, Ihre Trosse zu fieren",
	"lf1":"Ich kann keine Trosse mehr fieren",
	"lg":"Sie sollten sich bereitmachen, die Trosse(n) zu lösen",
	"lg1":"Ich mache mich bereit, die Trosse(n) zu lösen",
	"lg2":"Ich bin bereit, die Trosse(n) zu lösen",
	"lg3":"Sie sollten Trosse(n) auf Stb lösen",
	"lg4":"Ich habe Trosse(n) auf Stb gelöst",
	"lg5":"Sie sollten Trosse(n) auf Bb lösen",
	"lg6":"Ich habe Trosse(n) auf Bb gelöst",
	"lg7":"Sie sollten Trosse(n) lösen",
	"lg8":"Ich muss Trosse(n) lösen",
	"lh":"Höchstgeschwindigkeit im Schlepptau beträgt ... Knoten",
	"li":"Ich erhöhe die Geschwindigkeit",
	"li1":"Erhöhen Sie die Geschwindigkeit",
	"lj":"Ich verringere die Geschwindigkeit",
	"lj1":"Verringern Sie die Geschwindigkeit",
	"lk":"Tonne (oder Leuchtfeuer) wurde in Position ... aufgestellt",
	"ll":"Tonne (oder Leuchtfeuer) in Position ... wurde entfernt",
	"lm":"Angegebene Funkbake ist außer Betrieb",
	"ln":"Licht (Name) wurde gelöscht",
	"ln1":"Entlang dieser Küste (oder Küstenname) sind alle Lichter aus",
	"lo":"Ich bin nicht in meiner korrekten Position (gebraucht durch Feuerschiff)",
	"lo1":"Feuerschiff (Name) ist am falschen Ort",
	"lo2":"Feuerschiff (Name) wurde von seiner Stellung entfernt",
	"lp":"Es sind nicht weniger als ... (Meter/Fuß) Wasser auf der Bank",
	"lq":"Zur angegebenen Zeit werden ... (Meter/Fuß) Wasser auf der Bank sein",
	"lr":"Bank ist ungefährlich",
	"lr1":"Wie tief ist das Wasser auf der Bank?",
	"lr2":"Kann ich die Bank überqueren?",
	"ls":"Bank ist gefährlich",
	"lt":"Ihre Peilung von mir aus (oder von ... (Name/Erkennungszeichen)) ist ... (zur angegebenen Zeit)",
	"lu":"Die Peilung von ... (Name/Erkennungszeichen) ist von ... (Name/Erkennungszeichen) aus ... (zur angegebenen Zeit)",
	"lv":"Geben Sie mir meine Peilung von Ihnen aus. Ich werde mit Scheinwerfer aufleuchten",
	"lv1":"Wie ist meine Peilung von Ihnen (oder von ... (Name/Erkennungszeichen)) aus?",
	"lv2":"Wie ist die Peilung von ... (Name/Erkennungszeichen) von ... (Name/Erkennungszeichen) aus?",
	"lw":"Ich empfange Ihr Funksignal auf der Peilung ...",
	"lw1":"Können Sie mich per Funk anpeilen?",
	"lx":"Der Kanal/das Fahrwasser ist frei",
	"lx1":"Der Kanal/das Fahrwasser wird zur angegebenen Zeit frei sein",
	"lx2":"Sie können den Kanal/das Fahrwasser zur angegebenen Zeit befahren",
	"lx3":"Ist der Kanal/das Fahrwasser frei?",
	"lx4":"Wann kann ich den Kanal/das Fahrwasser befahren?",
	"ly":"Der Kanal/das Fahrwasser ist nicht frei",
	"lz":"Der Kanal/das Fahrwasser ist befahrbar",
	"lz1":"Ich beabsichtige, den Kanal/das Fahrwasser zu durchfahren",
	"lz2":"Ist der Kanal/das Fahrwasser befahrbar?",
	"lz3":"In welchem Zustand ist der Kanal/das Fahrwasser?",
	"lz4":"Was ist die geringste Tiefe im Kanal/Fahrwasser?",
	"ma":"Die geringste Tiefe im Kanal/Fahrwasser beträgt ... (Meter/Fuß)",
	"mb":"Sie sollten im Kanal/Fahrwasser mittig bleiben",
	"mb1":"Sie sollten auf der Stb-Seite des Kanals/Fahrwassers bleiben",
	"mb2":"Sie sollten auf der Bb-Seite des Kanals/Fahrwassers bleiben",
	"mb3":"Sie sollten den Kanal/das Fahrwasser freihalten",
	"mc":"Es gibt ein unbekanntes Hindernis im Kanal/Fahrwasser. Sie sollten vorsichtig fahren",
	"mc1":"Der Kanal/das Fahrwasser ist nicht befahrbar",
	"mc2":"Das Verkehrstrennungsgebiet ist auf der Spur ... nicht befahrbar",
	"md":"Mein Kurs beträgt ...",
	"md1":"Wie ist Ihr Kurs?",
	"me":"Der Kurs in Richtung ... (Standort) ist ...",
	"me1":"Wie ist der Kurs in Richtung ... (Standort)?",
	"mf":"Kurs, um mich zu erreichen, ist...",
	"mf1":"Wie ist der Kurs, um Sie zu erreichen?",
	"mg":"Sie sollten auf Kurs ... steuern",
	"mg1":"Auf welchen Kurs soll ich steuern?",
	"mh":"Sie sollten Kurs (zu angegebener Zeit) nach ... ändern",
	"mi":"Ich ändere Kurs nach ...",
	"mj":"Wrackteile, Gefährdung für Schifffahrt, in Position ... gemeldet",
	"mk":"Ich habe Wrackteile (in Position ... zu angegebener Zeit) gesichtet",
	"mk1":"Haben Sie Wrackteile oder Wrack gesehen?",
	"ml":"Wrackteile treiben nahe Position ... (oder Peilung/Entfernung von angegebenem Ort",
	"ml1":"Rumpf des Wracks ist unter Wasser",
	"ml2":"Rumpf des Wracks ist weit aus dem Wasser",
	"mm":"Es gibt ein Wrack in Position ...",
	"mm1":"Wrack ist betonnt",
	"mm2":"Wrack ist unter Wasser",
	"mn":"Wrack (in Position ...) ist nicht betonnt",
	"mo":"Ich bin (in Position ...) mit einer Untiefe oder einem Unterwassergegenstand kollidiert",
	"mp":"Ich bin in seichten Gewässern. Bitte weisen Sie mich an, wie ich navigieren soll",
	"mq":"Es besteht Strahlungsgefahr durch freigesetzte radioaktive Stoffe in diesem Gebiet (oder im Gebiet um Position ... ). Halten Sie Funkwache. Übermitteln Sie die Nachricht an andere Stationen in Ihrer Nähe",
	"mq1":"Der radioaktive Stoff ist in der Luft",
	"mq2":"Der radioaktive Stoff ist im Wasser",
	"mr":"Es besteht keine Strahlungsgefahr durch freigesetzte radioaktive Stoffe in diesem Gebiet (oder im Gebiet um Position ...) (mehr)",
	"mr1":"Besteht Strahlungsgefahr durch freigesetzte radioaktive Stoffe in diesem Gebiet (oder im Gebiet um Position ... )?",
	"ms":"Von meinem Fahrzeug geht gefährliche Strahlung aus",
	"ms1":"Von meinem Fahrzeug geht gefährliche Strahlung aus; Sie können sich von meiner Stb-Seite nähern",
	"ms2":"Von meinem Fahrzeug geht gefährliche Strahlung aus; Sie können sich von meiner Bb-Seite nähern",
	"ms3":"Von meinem Fahrzeug geht gefährliche Strahlung aus; Sie können sich von vorne nähern",
	"ms4":"Von meinem Fahrzeug geht gefährliche Strahlung aus; Sie können sich von achtern nähern",
	"mt":"Von meinem Fahrzeug geht gefährliche Strahlung aus; Sie können sich von (Himmelsrichtung oder unbekannter Richtung oder allen Richtungen) nähern",
	"mu":"Von meinem Fahrzeug geht gefährliche Strahlung aus; kommen Sie nicht näher als ... Kabellängen",
	"mv":"Mein Fahrzeug setzt radioaktive Stoffe frei und stellt eine Gefahr dar",
	"mw":"Mein Fahrzeug setzt radioaktive Stoffe frei und stellt eine Gefahr dar; kommen Sie nicht näher als ... Kabellängen",
	"mx":"Radioaktive Stoffe sind in der Luft. Nähern Sie sich nicht aus leewärtiger Richtung",
	"my":"Es ist gefährlich, anzuhalten",
	"my1":"Es ist gefährlich, in gegenwärtiger Position zu bleiben",
	"my2":"Es ist gefährlich, auf gegenwärtigem Kurs zu bleiben",
	"my3":"Es ist gefährlich fortzufahren, bevor Wetter sich bessert",
	"my4":"Es ist gefährlich, Kurs nach Stb zu ändern",
	"my5":"Es ist gefährlich, Kurs nach Bb zu ändern",
	"my6":"Es ist gefährlich, sich meinem Fahrzeug zu nähern",
	"my7":"Es ist gefährlich, Anker abzuwerfen oder zu trawlen",
	"my8":"Es ist gefährlich, brennbares Öl abzulassen",
	"mz":"Fahrt im Gebiet um Position ... ist gefährlich",
	"mz1":"Ich bin der Meinung, dass Sie eine gefährliche Navigationspraxis ausüben, und ich beabsichtige, Sie zu melden",
	"na":"Fahrt ist gesperrt",
	"na1":"Fahrt ist nur mit Hilfe durch Schlepper möglich",
	"na2":"Fahrt ist nur mit Hilfe durch Lotsen möglich",
	"na3":"Fahrt ist 500 Meter um diese Plattform herum verboten",
	"na4":"Fahrt ist 500 Meter um die Plattform in Peilrichtung ... von mir verboten",
	"na5":"Sie wurden bei der Fahrt innerhalb einer 500m-Sicherheitszone (um die Plattform in Peilrichtung ... von mir herum) erkannt und werden gemeldet",
	"na6":"Anker mit Tonnen erstrecken sich bis zu einer Meile von diesem Fahrzeug. Sie sollten sich freihalten",
	"nb":"In ihrer Fahrtrichtung (oder in angegebener Fahrtrichtung) gibt es Fischereiausrüstung",
	"nc":"Ich bin in Not und brauche dringend Hilfe",
	"nd":"Es wird eine Flutwelle erwartet. Sie sollten sich vorbereiten",
	"ne":"Sie sollten vorsichtig fahren",
	"ne1":"Sie sollten vorsichtig fahren; die Küste ist gefährlich",
	"ne2":"Sie sollten vorsichtig fahren; U-Boote exerzieren in diesem Gebiet",
	"ne3":"Sie sollten vorsichtig fahren; es ist eine Hafenkette gespannt",
	"ne4":"Sie sollten vorsichtig fahren; halten Sie sich vom Schussbereich frei",
	"ne5":"Sie sollten vorsichtig fahren; feindliches Fahrzeug (in Position ... ) gesichtet",
	"ne6":"Sie sollten vorsichtig fahren; feindliches U-Boot (in Position ... ) gesichtet",
	"ne7":"Sie sollten vorsichtig fahren; feindliches Flugzeug (in Position ... ) gesichtet",
	"nf":"Sie begeben sich in Gefahr",
	"nf1":"Sie begeben sich in Gefahr; es besteht Strahlungsgefahr",
	"ng":"Sie sind an einem gefährlichen Ort",
	"ng1":"Sie sind an einem gefährlichen Ort; es besteht Strahlungsgefahr",
	"nh":"Sie sind außer Gefahr",
	"nh1":"Sind Sie außer Gefahr?",
	"ni":"Ich habe (oder angegebenes Fahrzeug hat) Schlagseite von ... Grad nach Stb",
	"nj":"Ich habe (oder angegebenes Fahrzeug hat) Schlagseite von ... Grad nach Bb",
	"nk":"Das Wasser ist nicht tief genug",
	"nl":"Das Wasser ist tief genug",
	"nl1":"Ist das Wasser tief genug?",
	"nm":"Sie sollten die Wassertiefe um Ihr Fahrzeug herum melden",
	"nn":"Ich bin in ... (Fuß/Meter) tiefem Wasser",
	"no":"Negativ - \"Nein\" oder \"Die Bedeutung des vorigen Signals wird verneint\"",
	"np":"Die Wassertiefe am Bug beträgt ... (Fuß oder Meter)",
	"nq":"Die Wassertiefe am Heck beträgt ... (Fuß oder Meter)",
	"nr":"Die Wassertiefe an der Stb-Seite beträgt... (Fuß oder Meter)",
	"ns":"Die Wassertiefe an der Bb-Seite beträgt ... (Fuß oder Meter)",
	"nt":"Wie ist Ihr Tiefgang?",
	"nt1":"Wie ist Ihr unbeladener Tiefgang?",
	"nt2":"Wie ist Ihr Ballasttiefgang?",
	"nt3":"Wie ist Ihr beladener Tiefgang?",
	"nt4":"Wie ist Ihr Sommertiefgang?",
	"nt5":"Wie ist Ihr Wintertiefgang?",
	"nt6":"Wie ist Ihr maximaler Tiefgang?",
	"nt7":"Wie ist Ihr minimaler Tiefgang?",
	"nt8":"Wie ist Ihr Tiefgang vorne?",
	"nt9":"Wie ist Ihr Tiefgang achtern?",
	"nu":"Mein Tiefgang beträgt ... (Fuß oder Meter)",
	"nv":"Mein unbeladener Tiefgang beträgt ... (Fuß oder Meter)",
	"nw":"Mein Ballasttiefgang beträgt ... (Fuß oder Meter)",
	"nx":"Mein beladener Tiefgang beträgt ... (Fuß oder Meter)",
	"ny":"Mein Sommertiefgang beträgt ... (Fuß oder Meter)",
	"nz":"Mein Wintertiefgang beträgt ... (Fuß oder Meter)",
	"oa":"Mein maximaler Tiefgang beträgt ... (Fuß oder Meter)",
	"ob":"Mein minimaler Tiefgang beträgt ... (Fuß oder Meter)",
	"oc":"Mein Tiefgang vorne beträgt ... (Fuß oder Meter)",
	"od":"Mein Tiefgang hinten beträgt ... (Fuß oder Meter)",
	"oe":"Sie dürfen einen Tiefgang von ... (Fuß oder Meter) nicht überschreiten",
	"of":"Ich könnte zu einem Tiefgang von ... (Fuß oder Meter) leichtern",
	"og":"Bis zu welchem Tiefgang könnten Sie leichtern?",
	"oh":"Sie sollten Ihr Radar einschalten und Radarwache halten",
	"oh1":"Beschränkungen für den Radareinsatz sind aufgehoben",
	"oh2":"Verursacht mein Radar Störungen?",
	"oi":"Ich habe kein Radar",
	"oi1":"Sind Sie mit Radar ausgerüstet?",
	"oi2":"Ist Ihr Radar in Betrieb?",
	"oj":"Ich habe Sie auf meinem Radar in Peilung ..., Entfernung ... Meilen geortet",
	"oj1":"Ich kann Sie auf meinem Radar nicht orten",
	"oj2":"Sie sollten Ihren Kurs möglichst nach Stb ändern, um Radarortung zu ermöglichen",
	"oj3":"Sie sollten Ihren Kurs möglichst nach Bb ändern, um Radarortung zu ermöglichen",
	"oj4":"Können Sie mich per Radar orten?",
	"ok":"Korrekt",
	"ol":"Wird in diesem Hafen (oder angegebenem Hafen) Landradarberatung erteilt?",
	"om":"Peilrichtung und Entfernung des angegebenen Fahrzeugs (oder Gegenstands) per Radar beträgt ..., ... Meilen",
	"om1":"Wie ist die Peilung und Entfernung des angegebenen Fahrzeugs (oder Gegenstands) per Radar?",
	"on":"Ich habe ein Radarecho in Peilrichtung ..., Entfernung ... Meilen",
	"oo":"Mein Peilgerät ist außer Betrieb",
	"op":"Ich habe von ... (Name oder Erkennungszeichen) erbeten, zwei 10-sekündige Töne oder Trägerwelle seines Geräts gefolgt von seinem Erkennungszeichen zu übertragen",
	"op1":"Können Sie von ... (Name oder Erkennungszeichen) erbeten, zwei 10-sekündige Töne oder Trägerwelle seines Geräts gefolgt von seinem Erkennungszeichen zu übertragen?",
	"op2":"Können Sie zwei 10-sekündige Töne oder Trägerwelle Ihres Geräts gefolgt von Ihrem Erkennungszeichen übertragen?",
	"oq":"Ich kalibriere Peilgerät oder stelle Kompasse ein",
	"or":"Ich bin auf eine Mine getroffen",
	"os":"In diesem Gebiet (oder in angegebenem Gebiet) besteht Minengefahr",
	"os1":"Sie sollten nach Minen Ausschau halten",
	"os2":"Sie sind außerhalb der Minengefahrzone",
	"os3":"Bin ich außerhalb der Minengefahrzone?",
	"os4":"Sind Sie außerhalb der Minengefahrzone?",
	"os5":"Besteht in diesem Gebiet (oder in angegebenem Gebiet) Minengefahr?",
	"ot":"Mine wurde in Position ... (oder in angegebener Richtung) gesichtet",
	"ou":"Mine(n) wurde(n) in der Nähe (der in ungefährer Position ... ) gesichtet",
	"ov":"Mine(n) wird (werden) in Peilrichtung ..., Entfernung ... von mir vermutet",
	"ow":"Vor Ihnen liegt ein Minenfeld. Sie sollten anhalten und auf Anweisungen warten",
	"ow1":"Vor der Küste liegt ein Minenfeld. Sie sollten nicht zu nahe kommen",
	"ox":"Ungefähre Richtung des Minenfelds ist in Peilrichtung ... von mir",
	"oy":"Der Hafen ist vermint",
	"oy1":"Die Einfahrt ist vermint",
	"oy2":"Das Fahrwasser ist vermint",
	"oy3":"Gibt es Minen in der Hafeneinfahrt oder im Fahrwasser?",
	"oz":"Der minenbefreite Kanal ist ... (Fuß oder Meter) breit",
	"pa":"Ich werde den minenbefreiten Kanal anzeigen. Sie sollten in meinem Kielwasser fahren",
	"pa1":"Sie sollten sich vorsichtig im minenbefreiten Kanal halten",
	"pa2":"Der minenbefreite Kanal wird durch Tonnen markiert",
	"pa3":"Ich kann die Tonnen, die den minenbefreiten Kanal markieren, nicht sehen",
	"pa4":"Kennen Sie den minenbefreiten Kanal?",
	"pb":"Sie sollten sich von mir freihalten; ich führe Minenräumarbeiten durch",
	"pb1":"Sie sollten sich von mir freihalten; ich sprenge eine Seemine",
	"pc":"Ich habe Treibmine(n) vernichtet",
	"pc1":"Ich kann Treibmine(n) nicht vernichten",
	"pd":"Ihre Navigationslichter sind nicht zu sehen",
	"pd1":"Meine Navigationslichter funktionieren nicht",
	"pe":"Sie sollten alle Lichter außer die Navigationslichter ausschalten",
	"pg":"Ich sehe kein Licht",
	"pg1":"Sie sollten ein Licht hissen",
	"pg2":"Ihr Scheinwerfer blendet mich; schalten Sie ihn aus oder wenden Sie ihn ab",
	"ph":"Sie sollten so steuern, wie angezeigt",
	"ph1":"Sie sollten zu mir steuern",
	"ph2":"Ich steuere zu Ihnen",
	"ph3":"Sie sollten mehr nach Stb steuern",
	"ph4":"Ich steuere mehr nach Stb",
	"ph5":"Sie sollten mehr nach Bb steuren",
	"ph6":"Ich steure mehr nach Bb",
	"pi":"Sie sollten Ihren Kurs halten",
	"pi1":"Ich halte meinen Kurs",
	"pi2":"Soll ich meinen Kurs halten?",
	"pj":"Ich kann meinen Kurs nicht halten",
	"pk":"Ich kann nicht ohne Hilfe steuern",
	"pl":"Sie sollten direkt auf die Tonne (oder auf angegebenen Gegenstand) zusteuern",
	"pl1":"Sie sollten Tonne (oder angegebenen Gegenstand) auf Ihrer Stb-Seite halten",
	"pl2":"Sie sollten Tonne (oder angegebenen Gegenstand) auf Ihrer Bb-Seite halten",
	"pl3":"Sie können Tonne (oder angegebenen Gegenstand) auf beiden Seiten passieren",
	"pm":"Sie sollten in meinem Kielwasser fahren",
	"pm1":"Sie sollten vorfahren und den Kurs weisen",
	"pn":"Sie sollten sich leewärts von mir (oder von angegebenem Fahrzeug) halten",
	"pn1":"Sie sollten sich luvwärts von mir (oder von angegebenem Fahrzeug) halten",
	"pn2":"Sie sollten sich auf meiner Stb-Seite (oder Stb-Seite des angegebenen Fahrzeugs) halten",
	"pn3":"Sie sollten sich auf meiner Bb-Seite (oder Bb-Seite des angegebenen Fahrzeugs) halten",
	"po":"Sie sollten vor mir (oder angegebenem Fahrzeug) vorbeifahren",
	"po1":"Ich werde vor Ihnen (oder angegebenem Fahrzeug) vorbeifahren",
	"po2":"Sie sollten hinter mir (oder angegebenem Fahrzeug) vorbeifahren",
	"po3":"Ich werde hinter Ihnen (oder angegebenem Fahrzeug) vorbeifahren",
	"po4":"Sie sollten leewärts von mir (oder angegebenem Fahrzeug) vorbeifahren",
	"po5":"Ich werde leewärts von Ihnen (oder angegebenem Fahrzeug) vorbeifahren",
	"po6":"Sie sollten luvwärts von mir (oder angegebenem Fahrzeug) vorbeifahren",
	"po7":"Ich werde luvwärts von Ihnen (oder angegebenem Fahrzeug) vorbeifahren",
	"po8":"Sie sollten unter mein Heck kommen",
	"pp":"Halten Sie sich von mir frei",
	"pp1":"Überholen Sie mich nicht",
	"pp2":"Fahren Sie nicht vor mir vorbei",
	"pp3":"Fahren Sie nicht hinter mir vorbei",
	"pp4":"Fahren Sie nicht an meiner Stb-Seite vorbei",
	"pp5":"Fahren Sie nicht an meiner Bb-Seite vorbei",
	"pp6":"Fahren Sie nicht zu nah an mir vorbei",
	"pp7":"Sie sollten mir weichen",
	"pq":"Sie sollten sich näher an der Küste halten",
	"pq1":"Sie sollten sich von der Küste entfernen",
	"pq2":"Sie sollten in sicherem Abstand der Küste folgen",
	"pq3":"In welcher Entfernung von der Küste?",
	"pr":"Sie sollten sich näher an mir (oder an angegebenem Fahrzeug) halten",
	"pr1":"Sie sollten so nahe kommen wie möglich",
	"pr2":"Sie sollten sich in Sichtweite zu mir (oder angegebenem Fahrzeug) halten",
	"pr3":"Sie sollten sich in Rufweite zu mir (oder angegebenem Fahrzeug) halten",
	"ps":"Sie sollten nicht näher kommen",
	"ps1":"Sie sollten sich von mir fernhalten",
	"pt":"Wie ist der Stand der Gezeiten?",
	"pt1":"Die Flut kommt",
	"pt2":"Die Flut geht zurück",
	"pt3":"Die Flut ist flach",
	"pu":"Die Flut kommt zur angegebenen Zeit",
	"pu1":"Wann kommt die Flut?",
	"pv":"Die Flut geht zur angegebenen Zeit zurück",
	"pv1":"Wann geht die Flut zurück?",
	"pw":"Wie ist der Tidenhub?",
	"pw1":"Wie ist die Strömungsrichtung und Strömungsgeschwindigkeit der Tide?",
	"pw2":"Wie ist die Wassertiefe bei Flut und Ebbe hier (oder an angegebenem Ort)?",
	"px":"Der Tidenhub beträgt ... (Fuß oder Meter)",
	"py":"Die Strömungsrichtung der Tide beträgt ... Grad",
	"pz":"Die Strömungsgeschwindigkeit der Tide beträgt ... Knoten",
	"qa":"Wassertiefe bei Flut beträgt hier (oder an angegebenem Ort) ... (Fuß/Meter)",
	"qb":"Wassertiefe bei Ebbe beträgt hier (oder an angegebenem Ort) ... (Fuß/Meter)",
	"qc":"Sie sollten auf Flut warten",
	"qc1":"Sie sollten auf Ebbe warten",
	"qd":"Ich fahre voraus",
	"qd1":"Meine Maschinen fahren voraus",
	"qd2":"Ich werde weiter vorausfahren",
	"qd3":"Ich werde vorausfahren",
	"qd4":"Ich werde ganz langsam vorausfahren",
	"qe":"Ich mache Vorausfahrt",
	"qf":"Ich kann nicht vorausfahren",
	"qg":"Sie sollten vorausfahren",
	"qg1":"Sie sollten langsam vorausfahren",
	"qg2":"Sie sollten volle Kraft vorausfahren",
	"qg3":"Sie sollten weiter vorausfahren",
	"qg4":"Ihre Maschinen sollten weiter vorausfahren",
	"qh":"Sie sollten nicht weiter vorausfahren",
	"qi":"Ich fahre nach achtern",
	"qi1":"Meine Maschinen fahren nach achtern",
	"qi2":"Ich werde weiter nach achtern fahren",
	"qi3":"Ich werde nach achtern fahren",
	"qi4":"Ich werde ganz langsam nach achtern fahren",
	"qj":"Ich mache Fahrt nach achtern",
	"qk":"Ich kann nicht nach achtern fahren",
	"ql":"Sie sollten nach achtern fahren",
	"ql1":"Sie sollten langsam nach achtern fahren",
	"ql2":"Sie sollten volle Kraft nach achtern fahren",
	"ql3":"Sie sollten weiter nach achtern fahren",
	"ql4":"Ihre Maschinen sollten weiter nach achtern fahren",
	"qm":"Sie sollten nicht weiter nach achtern fahren",
	"qn":"Sie sollten längsseits an meiner Stb-Seite anlegen",
	"qn1":"Sie sollten längsseits an meiner Bb-Seite anlegen",
	"qn2":"Sie sollten vor Anker gehen, bevor Sie längsseits anlegen",
	"qo":"Sie sollten nicht längsseits anlegen",
	"qp":"Ich werde längsseits anlegen",
	"qp1":"Ich werde versuchen, längsseits anzulegen",
	"qq":"Ich benötige Gesundheitsfreigabe",
	"qr":"Ich kann nicht längsseits anlegen",
	"qr1":"Kann ich längsseits anlegen?",
	"qs":"Sie sollten zu angegebener Zeit vor Anker gehen",
	"qs1":"Sie sollten vor Anker gehen (wenn nötig Position anzeigen)",
	"qs2":"Sie sollten vor Anker gehen, um auf Schlepper zu warten",
	"qs3":"sie sollten beide Anker werfen",
	"qs4":"Sie sollten nach Belieben vor Anker gehen",
	"qs5":"Werden Sie vor Anker gehen?",
	"qt":"Sie sollten nicht vor Anker gehen; sie würden mit meinem Anker zusammenstoßen",
	"qu":"Ankern ist verboten",
	"qv":"Ich gehe in angegebener Position vor Anker",
	"qv1":"Ich habe beide Anker geworfen",
	"qw":"Ich werde nicht vor Anker gehen",
	"qw1":"Ich kann nicht vor Anker gehen",
	"qx":"Ich bitte um Ankererlaubnis",
	"qx1":"Sie haben Ankererlaubnis",
	"qy":"Ich wünsche, sofort vor Anker zu gehen",
	"qy1":"Wo soll ich vor Anker gehen?",
	"qz":"Sie sollten Ihre Anker wurfbereit halten",
	"qz1":"Sie sollten noch einen Anker werfen",
	"ra":"Mein Anker ist verfangen",
	"ra1":"Ich habe Telegrafenkabel mit meinem Anker eingehakt",
	"rb":"Ich treibe vor Anker",
	"rb1":"Sie scheinen vor Anker zu treiben",
	"rb2":"Sie drohen dort, wo Sie vor Anker liegen (oder vorhaben vor Anker zu gehen), zu treiben",
	"rc":"Ich reiße mich (oder angegebenes Fahrzeug reißt sich) los",
	"rc1":"Ich habe mich losgerissen",
	"rd":"Sie sollten Anker sofort lichten",
	"rd1":"Sie sollten Anker zu angegebener Zeit lichten",
	"rd2":"Ich kann meinen Anker nicht lichten",
	"re":"Sie sollten Ihren Ankerplatz/Liegeplatz wechseln; er ist unsicher",
	"rf":"Führen Sie mich zu einem sicheren Ankerplatz?",
	"rg":"Sie sollten ein Boot dorthin schicken, wo ich ankern oder anlegen soll",
	"rg1":"Zu welcher Zeit soll ich zum Ankerplatz kommen?",
	"rh":"In meiner Nähe (oder in der Nähe von Position ... ) ist der Grund nicht gut zum ankern geeignet",
	"ri":"In meiner Nähe (oder in der Nähe von Position ... ) ist der Grund gut zum ankern geeignet",
	"ri1":"Ist der Grund in Ihrer Nähe (oder in der Nähe von Position ... ) gut zum ankern geeignet?",
	"rj":"Sie sollten Ihre Maschinen bereit halten",
	"rj1":"Sie sollten Ihre Maschinen so schnell wie möglich bereit machen",
	"rj2":"Sie sollten melden, sobald Ihre Maschinen bereit sind",
	"rj3":"Sie sollten abfahren, sobald Ihre Maschinen bereit sind",
	"rj4":"Wann werden Ihre Maschinen bereit sein?",
	"rk":"Meine Maschinen werden zu angegebener Zeit bereit sein",
	"rk1":"Meine Maschinen sind bereit",
	"rl":"Sie sollten Ihre Maschinen sofort stoppen",
	"rl1":"Sie sollten Ihre Maschinen stoppen",
	"rm":"Meine Maschinen sind gestoppt",
	"rm1":"Ich stoppe meine Maschinen",
	"rm2":"Ich muss meine Maschinen stoppen",
	"rn":"Meine Maschinen sind außer Betrieb",
	"ro":"Meine Antriebswelle ist kaputt",
	"ro1":"In meiner Schraube hat sich Seil oder Tau verfangen",
	"ro2":"Ich habe meine Schraube verloren",
	"rp":"Landung ist hier sehr gefährlich",
	"rp1":"Landung ist hier sehr gefährlich; günstigerer Landeplatz liegt in angegebener Richtung",
	"rq":"Fragezeichen oder Interrogativ - voriges Signal ist als Frage zu verstehen",
	"rr":"Dies ist der günstigste Ort zum Landen",
	"rr1":"Flagge oder Licht werden am günstigsten Landeplatz gezeigt",
	"rs":"Es darf niemand an Bord",
	"rt":"Brechen Sie Ihr Manöver ab und achten Sie auf meine Signale",
	"rt1":"Welche Manöver beabsichtigen Sie?",
	"ru":"Ich bin manövrierbehindert; halten Sie Abstand",
	"ru1":"Ich führe Versuchsmanöver durch",
	"rv":"Sie sollten (zu angegebenem Ort) fahren",
	"rv1":"Sie sollten zum Fahrtziel fahren",
	"rv2":"Sie sollten zum Hafen fahren",
	"rv3":"Sie sollten zur See fahren",
	"rw":"Sie sollten zum Ankerplatz in angegebener Position fahren",
	"rx":"Sie sollten zur angezeiten Zeit fahren",
	"ry":"Sie sollten langsam fahren, wenn Sie mich überholen",
	"rz":"Sie sollten nicht (zu angegebenem Ort) fahren",
	"rz1":"Sie sollten nicht aus dem Hafen/dem Ankerplatz herausfahren",
	"sa":"Ich kann zur angegebenen Zeit fahren",
	"sb":"Ich fahre zum Unfallort",
	"sc":"Ich bin in Fahrt",
	"sc1":"Ich bin bereit, zu fahren",
	"sc2":"Ich werde in Fahrt sein, sobald Wetterlage es ermöglicht",
	"sd":"Ich bin nicht bereit, zu fahren",
	"sf":"Sind Sie (oder angegebenes Fahrzeug) in Fahrt?",
	"sf1":"Sind Sie bereit, zu fahren?",
	"sf2":"Wann werden Sie in Fahrt sein?",
	"sg":"Meine gegenwärtige Geschwindigkeit beträgt ... Knoten",
	"sj":"Meine Höchstgeschwindigkeit beträgt ... Knoten",
	"sl":"Wie ist Ihre gegenwärtige Geschwindigkeit?",
	"sl1":"Wie ist Ihre Höchstgeschwindigkeit?",
	"sm":"Ich führe Geschwindigkeitsversuche durch",
	"sn":"Sie sollten sofort anhalten. Versenken Sie Ihr Fahrzeug nicht, lassen Sie keine Boote ins Wasser, und funken Sie nicht. Wenn Sie nicht gehorchen, werde ich das Feuer auf Sie eröffnen",
	"so":"Sie sollten Ihr Fahrzeug sofort zum Stehen bringen",
	"so1":"Sie sollten Ihr Fahrzeug zum Stehen bringen und nach seewärts drehen",
	"so2":"Sie sollten bleiben, wo Sie sind",
	"sp":"Machen Sie keine Fahrt durchs Wasser",
	"sp1":"Meine Maschine ist gestoppt und ich mache keine Fahrt durchs Wasser",
	"sq":"Sie sollten halten oder beidrehen",
	"sq1":"Sie sollten halten oder beidrehen, sonst werde ich das Feuer auf Sie eröffnen",
	"sq2":"Sie sollten halten oder beidrehen; Ich schicke ein Boot zu Ihnen",
	"sq3":"Sie sollten halten oder beidrehen; Ich werde Ihr Fahrzeug besteigen",
	"st":"Was ist Ihre Ladung?",
	"su":"Ich habe Agrargüter geladen",
	"su1":"Ich habe Kohle geladen",
	"su2":"Ich habe Milchprodukte geladen",
	"su3":"Ich habe Obstprodukte geladen",
	"su4":"Ich habe schwere Maschinen geladen",
	"su5":"Ich habe Vieh geladen",
	"su6":"Ich habe Holz geladen",
	"su7":"Ich habe Öl/Ölprodukte geladen",
	"su8":"Ich habe Stückgut geladen",
	"sv":"Ich bin aufgrund verlagerter Fracht oder Ballast nicht seetauglich",
	"sw":"Ich lade/lösche/befördere gefährliche Güter",
	"sx":"Sie sollten kein Öl oder Ölgemisch löschen",
	"sy":"Löschen von Öl oder Ölgemisch ist in diesem Gebiet in einem Abstand von ... Meilen zum nächsten Land verboten ",
	"sz":"Es sind ... (Zahl) Personen an Bord",
	"ta":"Es sind noch ... (Zahl) Personen an Bord",
	"tb":"... (Zahl) Personen sind gestorben",
	"tc":"... (Zahl) Personen sind krank",
	"td":"Ich bin ein Fischtransporter",
	"td1":"Ich bin Mutterschiff für Fischereifahrzeuge",
	"td2":"Sind Sie ein Fischereifahrzeug?",
	"te":"Ich fische mit Grundschleppnetz",
	"te1":"Ich fische mit Schwimmschleppnetz",
	"te2":"Ich fische mit Langleine",
	"te3":"Ich fische mit Schleppleine",
	"te4":"Ich fische mit zwei Fahrzeugen",
	"te5":"Ich fische mit Treibnetzen",
	"te6":"Auf welche Weise fischen Sie?",
	"tf":"Ich werfe Beutelnetz",
	"tf1":"Ich werfe Treibnetze",
	"tf2":"Ich werfe Ringwadennetz",
	"tf3":"Ich werfe Schleppnetz",
	"tf4":"Ich werfe Langleinen",
	"tg":"Ich hole Beutelnetz ein",
	"tg1":"Ich hole Treibnetze ein",
	"tg2":"Ich hole Ringwadennetz ein",
	"tg3":"Ich hole Schleppnetz ein",
	"tg4":"Ich hole Langleinen ein",
	"th":"Sie sollten vorsichtig fahren. Es sind kleine Fischerboote in einem Umkreis von ... Meilen von mir unterwegs",
	"ti":"Sie sollten vorsichtig fahren. Sie treiben in Richtung meiner Netze",
	"tj":"Sie sollten vorsichtig fahren. Es sind Netze mit einer Tonne in der Gegend",
	"tk":"Ist auf meinem Kurs Fanggerät ausgelegt?",
	"tl":"Mein Fanggerät liegt nahe der Oberfläche in Richtung ... auf einer Distanz von ... Meilen",
	"tm":"Mein Fanggerät liegt weit unter der Oberfläche in Richtung ... auf einer Distanz von ... Meilen",
	"tn":"Auf welcher Richtung, Distanz, und Tiefe ist Ihr Fanggerät ausgelegt?",
	"to":"Ich habe eine Mine in meinem Räumgeschirr (oder Netz)",
	"tp":"Fanggerät hat sich in meiner Schraube verfangen",
	"tq":"Sie haben sich in meinem Fanggerät verfangen",
	"tq1":"Fanggerät muss zur Entwirrung eingeholt werden",
	"tq2":"Ich räume das Fanggerät",
	"tq3":"Sie sollten Maßnahmen treffen, um Fanggerät zu bergen",
	"ts":"Sie sollten Folgendes mit Ihren Schleppnetzleinen tun (angezeigt durch Zahl):",
	"ts1":"Fieren Sie die Schleppnetzleine auf der Bb-Seite",
	"ts2":"Fieren Sie die Schleppnetzleine auf der Stb-Seite",
	"ts3":"Fieren Sie beide Schleppnetzleinen",
	"ts4":"Fieren der Schleppnetzleinen stoppen",
	"ts5":"Holen Sie die Schleppnetzleine auf der Bb-Seite ein",
	"ts6":"Holen Sie die Schleppnetzleine auf der Stb-Seite ein",
	"ts7":"Holen Sie beide Schleppnetzleinen ein",
	"ts8":"Einholen der Schleppnetzleinen stoppen",
	"ts9":"Sie können die Schleppnetzleinen einholen; das Schleppnetz ist klar",
	"tu":"Ich muss die Schleppnetzleinen abschneiden. Das Schleppnetz ist verheddert",
	"tu1":"Geben Sie mir Ihre Schleppnetzleine, ich werde Ihr Fanggerät übernehmen",
	"tu2":"Ihre Schleppnetzleinen sind unter meinen",
	"tu3":"Meine Schleppnetzleinen sind beide gerissen",
	"tu4":"Meine Schleppnetzleine auf der Stb-Seite ist gerissen",
	"tu5":"Meine Schleppnetzleine auf der Bb-Seite ist gerissen",
	"tv":"In diesem Gebiet ist das Fischen verboten",
	"tv1":"In diesem Gebiet ist das Schleppnetzfischen gefährlich, da es ein Hindernis gibt",
	"tw":"Achtung! Sie sind in der Nähe einer Fischereiverbotszone",
	"tx":"Ein Fischereischutzboot befindet sich in Position ...",
	"ty":"Ich erbitte Unterstützung durch Fischereischutzboot",
	"tz":"Können Sie Unterstützung anbieten?",
	"ua":"Lotse wird zur angegebenen Zeit eintreffen",
	"ub":"Sie sollten beidrehen oder ankern, bis Lotse eintrifft",
	"uc":"Steht an diesem Ort (oder an angegebenem Ort) ein Lotse zur Verfügung?",
	"ue":"Wo kann ich einen Lotsen (falls nötig für angegebenes Fahrtziel) bekommen?",
	"uf":"Sie sollten Lotsenboot (oder angegebenem Fahrzeug) folgen",
	"ug":"Sie sollten in meinem Kielwasser steuern",
	"uh":"Können Sie mich zum Hafen führen?",
	"ui":"Die See ist zu unruhig; das Lotsenboot kann Sie nicht erreichen",
	"uj":"Machen Sie dem Lotsenboot Lee auf der Stb-Seite",
	"uj1":"Machen Sie dem Lotsenboot Lee auf der Bb-Seite",
	"uk":"Lotsenboot ist wahrscheinlich in Peilrichtung ... zu Ihnen",
	"uk1":"Haben Sie das Lotsenboot gesehen?",
	"ul":"Alle Fahrzeuge sollten so schnell wie möglich zur See fahren, da im Hafen Gefahr droht",
	"um":"Der Hafen (oder angegebener Hafen) ist für die Schifffahrt gesperrt",
	"un":"Sie dürfen sofort (oder zu angegebener Zeit) in den Hafen einfahren",
	"un1":"Darf ich in den Hafen einfahren?",
	"un2":"Darf ich aus dem Hafen ausfahren?",
	"uo":"Sie dürfen nicht in den Hafen einfahren",
	"up":"Erlaubnis zur Hafeneinfahrt wird dringend erbeten; ich habe einen Notfall",
	"uq":"Sie sollten außerhalb des Hafens (oder der Flussmündung) warten",
	"uq1":"Sie sollten bis zum Tageslicht außerhalb des Hafens warten",
	"ur":"Meine voraussichtliche Ankunftszeit (an angegebenem Ort) ist (angegebene Zeit)",
	"ur1":"Was ist Ihre voraussichtliche Ankunftszeit (an angegebenem Ort)?",
	"us":"Bis zur angegebenen Zeit kann nichts getan werden",
	"us1":"Bis zum Tageslicht kann nichts getan werden",
	"us2":"Bis zur Flut kann nichts getan werden",
	"us3":"Bis sich die Sichtverhältnisse bessern, kann nichts getan werden",
	"us4":"Bis sich das Wetter beruhigt, kann nichts getan werden",
	"us5":"Bis Tiefgang geleichtert wird, kann nichts getan werden",
	"us6":"Bis Schlepper eintreffen, kann nichts getan werden",
	"ut":"Wohin sind Sie unterwegs?",
	"ut1":"Von wo kommen Sie her?",
	"uu":"Ich bin unterwegs nach ...",
	"uv":"Ich komme aus ...",
	"uv1":"Ich führe eine friedliche Durchfahrt im Küstenmeer durch",
	"uv2":"Ihr Kurs führt in einen Bereich des Küstenmeeres, in dem das Recht auf friedliche Durchfahrt vorübergehend ausgesetzt ist",
	"uv3":"Sie sollten den Bereich des Küstenmeeres verlassen, in dem das Recht auf friedliche Durchfahrt vorübergehend ausgesetzt ist",
	"uv4":"Sie verstoßen gegen die Bedingungen der friedlichen Durchfahrt durch das Küstenmeer. Sie sind aufgefordert, die Bedingungen für die friedliche Durchfahrt durch das Küstenmeer einzuhalten",
	"uv5":"Ich verstoße nicht gegen die Bedingungen der friedlichen Durchfahrt durch das Küstenmeer",
	"uv6":"Ich habe aufgehört, gegen die Bedingungen der friedlichen Durchfahrt durch das Küstenmeer zu verstoßen",
	"uv7":"Da Sie unsere Aufforderung zur Einhaltung der Bedingungen der friedlichen Durchfahrt durch das Küstenmeer missachtet haben, sind Sie verpflichtet, das Küstenmeer unverzüglich zu verlassen",
	"uv8":"Ich befinde mich auf der Durchreise durch eine internationale Meerenge",
	"uv9":"Ich übe Schifffahrtsfreiheit aus",
	"uw":"Ich wünsche Ihnen eine angenehme Fahrt",
	"uw1":"Vielen Dank für Ihre Zusammenarbeit. Ich wünsche Ihnen eine angenehme Fahrt",
	"uw2":"Willkommen!",
	"uw3":"Willkommen zuhause!",
	"ux":"Keine Informationen verfügbar",
	"uy":"Ich führe Übungen durch. Halten Sie sich bitte von mir frei",
	"uz":"Ich habe noch für ... Stunden Bunkeröl",
	"vb":"Haben Sie genug Bunkeröl, um den Hafen zu erreichen?",
	"vc":"Wo ist der nächste Ort, an dem es Bunkeröl gibt?",
	"vc1":"Wo ist der nächste Ort, an dem es Dieselöl gibt?",
	"vc2":"Wo ist der nächste Ort, an dem es Kohle gibt?",
	"ve":"Ich desinfiziere mein Fahrzeug",
	"vf":"Sie sollten Ihr Erkennungszeichen hissen",
	"vg":"Der Bedeckungsgrad durch niedrige Wolken beträgt ... Achtel",
	"vh":"Die geschätzte Wolkenuntergrenze in Hunderten von Metern beträgt ... ",
	"vi":"Wie ist der Bedeckungsgrad durch niedrige Wolken in Achteln?",
	"vi1":"Wie ist die geschätzte Wolkenuntergrenze?",
	"vj":"Steife Brise (Windstärke 8-9) aus angegebener Richtung erwartet",
	"vk":"Sturm (Windstärke >10) aus angegebener Richtung erwartet",
	"vl":"Es nähert sich ein Tropensturm (Orkan, Wirbelsturm); Sie sollten Vorkehrungen treffen",
	"vm":"Tropensturm konzentriert sich um ... Uhr in Position ... auf Kurs ..., Geschwindigkeit ... Knoten",
	"vn":"Haben Sie neue Informationen zum Tropensturm (Positionsangabe falls nötig)?",
	"vo":"Sind Sie auf Eis gestoßen?",
	"vp":"Wie ist die Beschaffenheit des Eises, sein Entstehungsgrad, und seine Auswirkung auf die Schifffahrt?",
	"vq":"Die Beschaffenheit des Eises ist ... (Ziffer)",
	"vq0":"Kein Eis",
	"vq1":"Neueis (Eiskristalle, Matsch oder Schlamm, Pfannkucheneis oder Eisrinde)",
	"vq2":"Junges Festeis (5-15 cm dick)",
	"vq3":"Offenes Treibeis (nicht mehr als 5/8 der Wasseroberfläche ist mit Eisschollen bedeckt)",
	"vq4":"Eine zusammengedrückte Schlammansammlung (eine zusammengedrückte Masse aus Schlamm oder Pfannkucheneis, das Eis kann sich nicht ausbreiten)",
	"vq5":"Winterfesteis (mehr als 15 cm dick)",
	"vq6":"Dichtes Treibeis (Wasseroberfläche ist zu mehr als 5/8 von Eisschollen bedeckt)",
	"vq7":"Sehr dichtes Treibeis auf offener See",
	"vq8":"Packeis oder große, riesige, schwere Eisschollen",
	"vq9":"Eisrinne entlang Küste",
	"vr":"Eisentwicklung: (Ziffer)",
	"vr0":"Eisentwicklung unverändert",
	"vr1":"Eisentwicklung hat sich verbessert",
	"vr2":"Esentwicklung hat sich verschlechtert",
	"vr3":"Eis ist gebrochen",
	"vr4":"Eis hat sich geöffnet oder ist abgetrieben",
	"vr5":"Es hat sich neues Eis gebildet und/oder die Eisdicke hat zugenommen",
	"vr6":"Das Eis hat sich zusammengefroren",
	"vr7":"Eis ist in das Gebiet getrieben oder zusammengedrückt worden",
	"vr8":"Vorsicht vor Presseisrücken",
	"vr9":"Vorsicht vor Bildung von Presseisrücken",
	"vs":"Auswirkung des Eises auf die Schifffahrt: (Ziffer)",
	"vs0":"Schifffahrt durch Eis nicht behindert",
	"vs1":"Schifffahrt durch Eis für Maschinenfahrzeuge aus Eisen oder Stahl nicht behindert; gefährlich für hölzerne Fahrzeuge ohne Eisschutz",
	"vs2":"Schifffahrt für Kleinmaschinenfahrzeuge ohne Eisbrecherhilfe schwierig; gefährlich für Fahrzeuge von schwacher Konstruktion",
	"vs3":"Schifffahrt ohne Eisbrecher nur für stark konstruierte Fahrzeuge mit leistungsfähigen Maschinen",
	"vs4":"Eisbrecherhilfe bei Bedarf verfügbar",
	"vs5":"Fahren Sie ohne Eisbrecherhilfe durch den Kanal",
	"vs6":"Nur mit Eisbrecherhilfe möglich",
	"vs7":"Eisbrecher kann nur für Fahrt durch Eis verstärkten Fahrzeugen helfen",
	"vs8":"Vorübergehend für die Schifffahrt gesperrt",
	"vs9":"Schifffahrt ist eingestellt",
	"vt":"Gefahr von Eisansatz am Aufbau",
	"vt1":"Ich habe schwere Eisbildung am Aufbau",
	"vu":"Ich habe in Position ... ein Eisfeld gesichtet",
	"vv":"Eisbrecher ist nicht auf Station",
	"vv1":"Eisbrecher ist auf Station",
	"vw":"Ich habe Eisberge in Position ... gesichtet",
	"vx":"Ich habe einen oder mehrere Eisberge gesichtet (mit oder ohne Zeit- und Positionsangabe)",
	"vy":"Es wurde(n) ein oder mehrere Eisberge gemeldet (mit oder ohne Zeit- und Positionsangabe)",
	"vz":"Schifffahrt ist im Gebiet um Position ... aufgrund von Eisbergen gefährlich",
	"vz1":"Schifffahrt ist im Gebiet um Position ... aufgrund von Treibeis gefährlich",
	"vz2":"Schifffahrt ist im Gebiet um Position ... aufgrund von Packeis gefährlich",
	"wa":"Wiederholen Sie Wort oder Gruppe nach ...",
	"wb":"Wiederholen Sie Wort oder Gruppe vor ...",
	"wc":"Ich sitze (oder angegebenes Fahrzeug sitzt) auf Eis fest und benötige/t Eisbrecherhilfe",
	"wc1":"Eisbrecher kommt Ihnen zur Hilfe",
	"wd":"Eisbrecher steht nicht zur Verfügung",
	"wd1":"Eisbrecher kann derzeit nicht helfen",
	"we":"Schifffahrtskanal wird durch Eisbrecher offen gehalten",
	"wf":"Ich kann Eisbrecherhilfe nur bis zur Position ... geben",
	"wg":"Offener Kanal oder offenes Gebiet befindet sich in Flugrichtung des Flugzeugs",
	"wh":"Ich kann nur helfen, wenn Sie sich alle Mühe geben, zu folgen",
	"wi":"Zu welcher Zeit werden Sie mit Höchstgeschwindigkeit folgen?",
	"wj":"Der Konvoi wird zur angegebenen Zeit von hier (oder von Position ... ) starten",
	"wk":"Sie (oder angegebenes Fahrzeug) werden Nummer ... im Konvoi sein",
	"wl":"Eisbrecher setzt während der Dunkelheit die Arbeit aus",
	"wm":"Unterstützung durch Eisbrecher beginnt jetzt. Nutzen Sie spezielle Eisbrecher-Hilfssignale und halten Sie ständig Ausschau nach akustischen, visuellen, oder Funksignalen",
	"wn":"Eisbrecher setzt für ... Stunden die Arbeit aus, oder bis günstigere Bedingungen eintreffen",
	"wo":"Eisbrecherunterstützung ist vollendet. Fahren Sie weiter zu Ihrem Fahrtziel",
	"wp":"Barometer hält sich",
	"wp1":"Barometer fällt rasant",
	"wp2":"Barometer steigt rasant",
	"wq":"Das Barometer ist in den letzten drei Stunden um ... Millibar gefallen",
	"wr":"Das Barometer ist in den letzten drei Stunden um ... Millibar gestiegen",
	"ws":"Der korrigierte Luftdruck auf dem Meeresspiegel beträgt ... Millibar",
	"ws1":"Nennen Sie den korrigierten Lufdruck auf dem Meeresspiegel in Millibar",
	"wt":"Sehr tiefes Tiefdruckgebiet nähert sich aus angegebener Richtung",
	"wu":"Es gibt Anhaltspunkte, dass sich in Position ... ein Tiefdruckgebiet bildet",
	"wv":"Die Lufttemperatur ist unter Null (Celsius)",
	"wv1":"Es wird eine Lufttemperatur von unter Null (Celsius) erwartet",
	"ww":"Wie ist der Seegang in Ihrer Umgebung (oder im Bereich der Position ... )?",
	"wx":"Die Richtung der Meeresströmung beträgt ... Zehnergrade",
	"wy":"Die See ist ... (Ziffer auf der Seegangsskala)",
	"wy0":"Die See ist glatt (0m Wellenhöhe)",
	"wy1":"Die See ist ruhig (0 - 0,1m Wellenhöhe)",
	"wy2":"Die See ist schwach bewegt (0,1 - 0,5m Wellenhöhe)",
	"wy3":"Die See ist leicht bewegt (0,5 - 1,25m Wellenhöhe)",
	"wy4":"Die See ist mäßig bewegt (1,25 - 2,5m Wellenhöhe)",
	"wy5":"Die See ist grob (2,5-4m Wellenhöhe)",
	"wy6":"Die See ist sehr grob (4-6m Wellenhöhe)",
	"wy7":"Die See ist hoch (6-9m Wellenhöhe)",
	"wy8":"Die See ist sehr hoch (9-14m Wellenhöhe)",
	"wy9":"Die See ist außergewöhnlich schwer (>14m Wellenhöhe)",
	"wz":"Wie soll der Seegang in meiner Umgebung (oder im Bereich von Position) sein?",
	"xa":"Die Richtung der Meeresströmung soll ... Zehnergrade betragen",
	"xb":"Die See soll ... (Ziffer auf der Seegangsskala) sein",
	"xb0":"Die See soll glatt (0m Wellenhöhe) sein",
	"xb1":"Die See soll ruhig (0 - 0,1m Wellenhöhe) sein",
	"xb2":"Die See soll schwach bewegt (0,1 - 0,5m Wellenhöhe) sein",
	"xb3":"Die See soll leicht bewegt (0,5 - 1,25m Wellenhöhe) sein",
	"xb4":"Die See soll mäßig bewegt (1,25 - 2,5m Wellenhöhe) sein",
	"xb5":"Die See soll grob (2,5-4m Wellenhöhe) sein",
	"xb6":"Die See soll sehr grob (4-6m Wellenhöhe) sein",
	"xb7":"Die See soll hoch (6-9m Wellenhöhe) sein",
	"xb8":"Die See soll sehr hoch (9-14m Wellenhöhe) sein",
	"xb9":"Die See soll außergewöhnlich schwer (>14m Wellenhöhe) sein",
	"xc":"Wie ist die Dünung in Ihrer Umgebung (oder im Bereich der Position ... )?",
	"xd":"Die Wellenrichtung in Zehnergraden beträgt ... ",
	"xe":"Die Dünung ist... (Ziffer auf der Dünungsskala)",
	"xe0":"Keine Dünung",
	"xe1":"Die Dünung ist sehr gering",
	"xe2":"Die Dünung ist gering",
	"xe3":"Die Dünung ist leicht",
	"xe4":"Die Dünung ist moderat",
	"xe5":"Die Dünung ist moderat stürmisch",
	"xe6":"Die Dünung ist stürmisch",
	"xe7":"Die Dünung ist hoch",
	"xe8":"Die Dünung ist sehr hoch",
	"xe9":"Die Dünung ist unregelmäßig",
	"xf":"Wie soll die Dünung in meiner Umgebung (oder im Bereich der Position ... ) sein?",
	"xg":"Die Wellenrichtung soll in Zehnergraden ... betragen",
	"xh":"Die Dünung soll ... sein (Ziffer auf der Dünungsskala)",
	"xh1":"Die Dünung soll sehr gering",
	"xh2":"Die Dünung soll gering sein",
	"xh3":"Die Dünung soll leicht sein",
	"xh4":"Die Dünung soll moderat sein",
	"xh5":"Die Dünung soll moderat stürmisch sein",
	"xh6":"Die Dünung soll stürmisch sein",
	"xh7":"Die Dünung soll hoch sein",
	"xh8":"Die Dünung soll sehr hoch sein",
	"xh9":"Die Dünung soll unregelmäßig sein",
	"xi":"Zeigen Sie die Sichtweite an",
	"xj":"Sichtweite beträgt ... Zehntelseemeilen",
	"xk":"Sichtweite beträgt zwischen ... und ... Zehntelseemeilen",
	"xl":"Sichtweite nimmt ab",
	"xl1":"Sichtweite nimmt zu",
	"xl2":"Sichtweite schwankt",
	"xm":"Wie soll die Sichtweite in meiner Umgebung (oder im Bereich der Position ... ) sein?",
	"xn":"Sichtweite soll ... Zehntelseemeilen sein",
	"xo":"Sichtweite soll abnehmen",
	"xo1":"Sichtweite soll zunehmen",
	"xo2":"Sichtweite soll schwanken",
	"xp":"Ich (oder angegebenes Fahrzeug) ist im Nebel gestoppt",
	"xp1":"Ich befahre Gebiet mit eingeschränkter Sicht",
	"xq":"In welchen Wetterbedingungen befinden Sie sich?",
	"xr":"Das Wetter ist gut",
	"xr1":"Das Wetter ist schlecht",
	"xr2":"Das Wetter beruhigt sich",
	"xr3":"Das Wetter verschlechtert sich",
	"xs":"Wetterbericht ist nicht verfügbar",
	"xt":"Es wird schlechtes Wetter erwartet",
	"xt1":"Es wird gutes Wetter erwartet",
	"xt2":"Es wird gleichbleibendes Wetter erwartet",
	"xt3":"Wie soll das Wetter werden?",
	"xu":"Sie sollten warten, bis sich das Wetter beruhigt",
	"xu1":"Ich werde warten, bis sich das Wetter beruhigt",
	"xv":"Bitte geben Sie mir einen Wetterbericht für meine Umgebung (oder Bereich um Position ... ) durch",
	"xw":"Wie ist die Windstärke und Windrichtung in ihrer Umgebung (oder im Bereich um Position ... )?",
	"xx":"Die Windrichtung ist ... (Himmelsrichtung)",
	"xy":"Es herrscht Windstärke ... (Zahl auf der Beaufort-Skala)",
	"xz":"Was tut der Wind?",
	"xz1":"Der Wind dreht links",
	"xz2":"Der Wind dreht rechts",
	"xz3":"Der Wind nimmt zu",
	"xz4":"Der Wind ist böig",
	"xz5":"Der Wind weht stetig",
	"xz6":"Der Wind lässt nach",
	"ya":"Wie soll die Windstärke und Windrichtung in meiner Umgebung (oder im Bereich um Position ... ) sein?",
	"yb":"Windrichtung soll... (Himmelsrichtung) sein",
	"yc":"Windstärke soll ... (Zahl auf der Beaufort-Skala) betragen",
	"yd":"Was soll der Wind tun?",
	"yd1":"Der Wind soll linksdrehen",
	"yd2":"Der Wind soll rechtsdrehen",
	"yd3":"Der Wind soll zunehmen",
	"yd4":"Der Wind soll böig werden",
	"yd5":"Der Wind soll stetig wehen",
	"yd6":"Der Wind soll nachlassen",
	"yg":"Sie scheinen gegen das Verkehrstrennungsgebiet zu verstoßen",
	"yh":"Ich habe Folgendes von (Name oder Identifizierungszeichen der Station) erhalten",
	"yi":"Ich habe die Sicherheitsmeldung von (Name oder Identifizierungszeichen) erhalten",
	"yj":"Haben Sie die Sicherheitsmeldung von (Name oder Identifizierungszeichen) erhalten?",
	"yk":"Ich kann Ihre Frage nicht beantworten",
	"yl":"Ich werde Sie um ... Uhr (auf Kanal ... ) wieder anrufen",
	"ym":"Wer ruft mich?",
	"yn":"Stornieren Sie meine letzte Nachricht",
	"yo":"Ich werde mit (Handflaggen/Megafon/Signalscheinwerfer/akustischen Signalen/...) kommunizieren",
	"yp":"Ich wünsche mit Station (Identifizierungszeichen) mit (Handflaggen/Megafon/Signalscheinwerfer/akustischen Signalen/...) zu kommunizieren",
	"yq":"Ich wünsche mit (Handflaggen/Megafon/Signalscheinwerfer/akustischen Signalen/...) mit Fahrzeug in Peilrichtung ... von mir zu kommunizieren",
	"yr":"Können Sie mit (Handflaggen/Megafon/Signalscheinwerfer/akustischen Signalen/...) kommunizieren?",
	"ys":"Ich kann nicht mit (Handflaggen/Megafon/Signalscheinwerfer/akustischen Signalen/...) kommunizieren",
	"yt":"Ich kann Ihre (Handflaggen/Megafon/Signalscheinwerfer/akustischen Signale/...) nicht hören/sehen",
	"yu":"Ich werde mit Ihrer Station gemäß INTERCO kommunizieren",
	"yv":"Die folgenden Signale sind INTERCO-Signale",
	"yv1":"Die folgenden Signale sind örtliche Signale",
	"yw":"Ich wünsche auf angegebener Frequenz per Funktelegrafie kommunizieren",
	"yx":"Ich wünsche auf angegebener Frequenz per Sprechfunk zu kommunizieren",
	"yy":"Ich wünsche auf angegebener Frequenz per UKW-Sprechfunk zu kommunizieren",
	"yz":"Die folgenden Wörter sind in normaler Sprache",
	"za":"Ich wünsche mit Ihnen auf ... (Sprachangabe durch Ziffer) zu kommunizieren",
	"za0":"Ich wünsche mit Ihnen auf Niederländisch zu kommunizieren",
	"za1":"Ich wünsche mit Ihnen auf Englisch zu kommunizieren",
	"za2":"Ich wünsche mit Ihnen auf Französisch zu kommunizieren",
	"za3":"Ich wünsche mit Ihnen auf Deutsch zu kommunizieren",
	"za4":"Ich wünsche mit Ihnen auf Griechisch zu kommunizieren",
	"za5":"Ich wünsche mit Ihnen auf Italienisch zu kommunizieren",
	"za6":"Ich wünsche mit Ihnen auf Japanisch zu kommunizieren",
	"za7":"Ich wünsche mit Ihnen auf Norwegisch zu kommunizieren",
	"za8":"Ich wünsche mit Ihnen auf Russisch zu kommunizieren",
	"za9":"Ich wünsche mit Ihnen auf Spanisch zu kommunizieren",
	"zb":"Ich kann mit Ihnen auf ... (Sprachangabe durch Ziffer) kommunizieren",
	"zb0":"Ich kann mit Ihnen auf Niederländisch kommunizieren",
	"zb1":"Ich kann mit Ihnen auf Englisch kommunizieren",
	"zb2":"Ich kann mit Ihnen auf Französisch  kommunizieren",
	"zb3":"Ich kann mit Ihnen auf Deutsch kommunizieren",
	"zb4":"Ich kann mit Ihnen auf Griechisch kommunizieren",
	"zb5":"Ich kann mit Ihnen auf Italienisch kommunizieren",
	"zb6":"Ich kann mit Ihnen auf Japanisch kommunizieren",
	"zb7":"Ich kann mit Ihnen auf Norwegisch kommunizieren",
	"zb8":"Ich kann mit Ihnen auf Russisch kommunizieren",
	"zb9":"Ich kann mit Ihnen auf Spanisch kommunizieren",
	"zc":"Können Sie mit mir auf ... (Sprachangabe durch Ziffer) kommunizieren?",
	"zc0":"Können Sie mit mir auf Niederländisch kommunizieren?",
	"zc1":"Können Sie mit mir auf Englisch kommunizieren?",
	"zc2":"Können Sie mit mir auf Französisch kommunizieren?",
	"zc3":"Können Sie mit mir auf Deutsch kommunizieren?",
	"zc4":"Können Sie mit mir auf Griechisch kommunizieren?",
	"zc5":"Können Sie mit mir auf Italienisch kommunizieren?",
	"zc6":"Können Sie mit mir auf Japanisch kommunizieren?",
	"zc7":"Können Sie mit mir auf Norwegisch kommunizieren?",
	"zc8":"Können Sie mit mir auf Russisch kommunizieren?",
	"zc9":"Können Sie mit mir auf Spanisch kommunizieren?",
	"zd":"Bitte übermitteln Sie Folgendes an alle Schiffe in der Gegend",
	"zd1":"Bitte melden Sie mich an die Küstenwache New York",
	"zd2":"Bitte melden Sie mich an Lloyd's London",
	"zd3":"Bitte melden Sie mich an Minmorflot in Moskau",
	"zd4":"Bitte melden Sie mich an MSA Tokyo",
	"ze":"Sie sollten in Sichtweite kommen",
	"zf":"Ich möchte mit Ihnen Signale üben",
	"zg":"Es ist gerade ungünstig, Signale zu üben",
	"zh":"Übung ist vollendet",
	"zi":"Ich kann mit (Handflaggen/Megafon/Signalscheinwerfer/akustischen Signalen/...) empfangen, aber nicht übertragen",
	"zj":"Ich kann mit (Handflaggen/Megafon/Signalscheinwerfer/akustischen Signalen/...) übertragen, aber nicht empfangen",
	"zk":"Ich kann Ihr Signal nicht entziffern. Bitte wiederholen Sie es mit Handflaggen/Megafon/Signalscheinwerfer/akustischen Signalen/...)",
	"zl":"Ihr Signal wurde empfangen, aber nicht verstanden",
	"zm":"Sie sollten langsamer übertragen (oder sprechen)",
	"zm1":"Soll ich langsamer übertragen (oder sprechen)?",
	"zn":"Sie sollten jedes Wort oder jede Gruppe zweimal übertragen",
	"zo":"Sie sollten aufhören, zu übertragen",
	"zo1":"Soll ich aufhören, zu übertragen?",
	"zp":"Mein letztes Signal war falsch. Ich werde es korrekt wiederholen",
	"zq":"Ihr Signal scheint falsch kodiert zu sein; sie sollten es prüfen und wiederholen",
	"zr":"Wiederholen Sie das Signal, das gerade an mich von Station (Identifizierungszeichen) übertragen wird",
	"zs":"An Bord ist alles gesund; ich bitte um freie Verkehrserlaubnis",
	"zt":"In meiner Seegesundheitserklärung sind alle Gesundheitsfragen negativ beantwortet",
	"zu":"In meiner Seegesundheitserklärung ist/sind Frage(n) ... (Nummer) positiv beantwortet",
	"zv":"Ich glaube, in den letzten dreißig Tagen in einem Seuchengebiet gewesen zu sein",
	"zw":"Ich brauche Hafenarzt",
	"zw1":"Hafenarzt wird (zur angegebenen Zeit) verfügbar sein",
	"zx":"Sie sollten das passende Verkehrserlaubnissignal geben",
	"zy":"Sie haben Verkehrserlaubnis",
	"zz":"Sie sollten für Gesundheitskontrolle zum Ankerplatz (Ortsangabe) fahren",
	"zz1":"Wo ist der Ankerplatz für die Gesundheitskontrolle?"
}

const inter_map = new Map(Object.entries(inter));
const alfa_map = new Map(Object.entries(alfa));
const flags_map = new Map(Object.entries(flags));

function format_an(){
        var alfa_data = [];
        var img = [];
        document.getElementById("flag-container").innerHTML = "";
        document.getElementById("alfa-container").innerHTML = "";
        document.getElementById("inter-container").innerHTML = "";
        var str = document.getElementById("eing").value;
        if (!(str.match(/^[a-z0-9]*$/i))){
                document.getElementById("alfa-container").innerHTML = "<span id=\"a0w\">Geben Sie nur alphanumerische Zeichen ein</span>";
                return;
        }
        str = str.toLowerCase();
        var inter_data = inter_map.get(str);
        if (inter_data == null){inter_data = "<i>Bedeutung nicht bekannt</i>";}
        var chars = Array.from(str);
        chars.forEach(
                (item, index) => {
                        alfa_data.push(alfa_map.get(item));
                        img.push(document.createElement("img"));
                        img[index].src = flags_map.get(item);
                        img[index].className = "Flagge";
                        document.getElementById("alfa-container").innerHTML = alfa_data.join(" ");
                        document.getElementById("flag-container").appendChild(img[index]);
                        }
        );
        if(str){
        document.getElementById("inter-container").innerHTML = inter_data;
        }

}
